// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/ai.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AIInsight represents a single optimization suggestion or analysis result.
type AIInsight struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Severity       string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // "info", "warning", "critical"
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // "security", "performance", "availability"
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIInsight) Reset() {
	*x = AIInsight{}
	mi := &file_gateon_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIInsight) ProtoMessage() {}

func (x *AIInsight) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIInsight.ProtoReflect.Descriptor instead.
func (*AIInsight) Descriptor() ([]byte, []int) {
	return file_gateon_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AIInsight) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AIInsight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AIInsight) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AIInsight) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AIInsight) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type AnalyzeConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: focus analysis on a specific area.
	Focus         string `protobuf:"bytes,1,opt,name=focus,proto3" json:"focus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeConfigRequest) Reset() {
	*x = AnalyzeConfigRequest{}
	mi := &file_gateon_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeConfigRequest) ProtoMessage() {}

func (x *AnalyzeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeConfigRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeConfigRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeConfigRequest) GetFocus() string {
	if x != nil {
		return x.Focus
	}
	return ""
}

type AnalyzeConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insights      []*AIInsight           `protobuf:"bytes,1,rep,name=insights,proto3" json:"insights,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeConfigResponse) Reset() {
	*x = AnalyzeConfigResponse{}
	mi := &file_gateon_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeConfigResponse) ProtoMessage() {}

func (x *AnalyzeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeConfigResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeConfigResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeConfigResponse) GetInsights() []*AIInsight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *AnalyzeConfigResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ChatWithAIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ContextFiles  []string               `protobuf:"bytes,2,rep,name=context_files,json=contextFiles,proto3" json:"context_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatWithAIRequest) Reset() {
	*x = ChatWithAIRequest{}
	mi := &file_gateon_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatWithAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatWithAIRequest) ProtoMessage() {}

func (x *ChatWithAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatWithAIRequest.ProtoReflect.Descriptor instead.
func (*ChatWithAIRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ChatWithAIRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatWithAIRequest) GetContextFiles() []string {
	if x != nil {
		return x.ContextFiles
	}
	return nil
}

type ChatWithAIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatWithAIResponse) Reset() {
	*x = ChatWithAIResponse{}
	mi := &file_gateon_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatWithAIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatWithAIResponse) ProtoMessage() {}

func (x *ChatWithAIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatWithAIResponse.ProtoReflect.Descriptor instead.
func (*ChatWithAIResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ChatWithAIResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_gateon_v1_ai_proto protoreflect.FileDescriptor

const file_gateon_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x12gateon/v1/ai.proto\x12\tgateon.v1\"\xa3\x01\n" +
	"\tAIInsight\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation\",\n" +
	"\x14AnalyzeConfigRequest\x12\x14\n" +
	"\x05focus\x18\x01 \x01(\tR\x05focus\"c\n" +
	"\x15AnalyzeConfigResponse\x120\n" +
	"\binsights\x18\x01 \x03(\v2\x14.gateon.v1.AIInsightR\binsights\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"R\n" +
	"\x11ChatWithAIRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rcontext_files\x18\x02 \x03(\tR\fcontextFiles\"*\n" +
	"\x12ChatWithAIResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2\xaa\x01\n" +
	"\tAIService\x12R\n" +
	"\rAnalyzeConfig\x12\x1f.gateon.v1.AnalyzeConfigRequest\x1a .gateon.v1.AnalyzeConfigResponse\x12I\n" +
	"\n" +
	"ChatWithAI\x12\x1c.gateon.v1.ChatWithAIRequest\x1a\x1d.gateon.v1.ChatWithAIResponseB5Z3github.com/gsoultan/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_ai_proto_rawDescOnce sync.Once
	file_gateon_v1_ai_proto_rawDescData []byte
)

func file_gateon_v1_ai_proto_rawDescGZIP() []byte {
	file_gateon_v1_ai_proto_rawDescOnce.Do(func() {
		file_gateon_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_ai_proto_rawDesc), len(file_gateon_v1_ai_proto_rawDesc)))
	})
	return file_gateon_v1_ai_proto_rawDescData
}

var file_gateon_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gateon_v1_ai_proto_goTypes = []any{
	(*AIInsight)(nil),             // 0: gateon.v1.AIInsight
	(*AnalyzeConfigRequest)(nil),  // 1: gateon.v1.AnalyzeConfigRequest
	(*AnalyzeConfigResponse)(nil), // 2: gateon.v1.AnalyzeConfigResponse
	(*ChatWithAIRequest)(nil),     // 3: gateon.v1.ChatWithAIRequest
	(*ChatWithAIResponse)(nil),    // 4: gateon.v1.ChatWithAIResponse
}
var file_gateon_v1_ai_proto_depIdxs = []int32{
	0, // 0: gateon.v1.AnalyzeConfigResponse.insights:type_name -> gateon.v1.AIInsight
	1, // 1: gateon.v1.AIService.AnalyzeConfig:input_type -> gateon.v1.AnalyzeConfigRequest
	3, // 2: gateon.v1.AIService.ChatWithAI:input_type -> gateon.v1.ChatWithAIRequest
	2, // 3: gateon.v1.AIService.AnalyzeConfig:output_type -> gateon.v1.AnalyzeConfigResponse
	4, // 4: gateon.v1.AIService.ChatWithAI:output_type -> gateon.v1.ChatWithAIResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateon_v1_ai_proto_init() }
func file_gateon_v1_ai_proto_init() {
	if File_gateon_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_ai_proto_rawDesc), len(file_gateon_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateon_v1_ai_proto_goTypes,
		DependencyIndexes: file_gateon_v1_ai_proto_depIdxs,
		MessageInfos:      file_gateon_v1_ai_proto_msgTypes,
	}.Build()
	File_gateon_v1_ai_proto = out.File
	file_gateon_v1_ai_proto_goTypes = nil
	file_gateon_v1_ai_proto_depIdxs = nil
}
