// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: gateon/v1/ai.proto

package gateonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_AnalyzeConfig_FullMethodName = "/gateon.v1.AIService/AnalyzeConfig"
	AIService_ChatWithAI_FullMethodName    = "/gateon.v1.AIService/ChatWithAI"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	AnalyzeConfig(ctx context.Context, in *AnalyzeConfigRequest, opts ...grpc.CallOption) (*AnalyzeConfigResponse, error)
	ChatWithAI(ctx context.Context, in *ChatWithAIRequest, opts ...grpc.CallOption) (*ChatWithAIResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) AnalyzeConfig(ctx context.Context, in *AnalyzeConfigRequest, opts ...grpc.CallOption) (*AnalyzeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeConfigResponse)
	err := c.cc.Invoke(ctx, AIService_AnalyzeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ChatWithAI(ctx context.Context, in *ChatWithAIRequest, opts ...grpc.CallOption) (*ChatWithAIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatWithAIResponse)
	err := c.cc.Invoke(ctx, AIService_ChatWithAI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	AnalyzeConfig(context.Context, *AnalyzeConfigRequest) (*AnalyzeConfigResponse, error)
	ChatWithAI(context.Context, *ChatWithAIRequest) (*ChatWithAIResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) AnalyzeConfig(context.Context, *AnalyzeConfigRequest) (*AnalyzeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeConfig not implemented")
}
func (UnimplementedAIServiceServer) ChatWithAI(context.Context, *ChatWithAIRequest) (*ChatWithAIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatWithAI not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_AnalyzeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AnalyzeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AnalyzeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AnalyzeConfig(ctx, req.(*AnalyzeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ChatWithAI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatWithAIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ChatWithAI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ChatWithAI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ChatWithAI(ctx, req.(*ChatWithAIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateon.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeConfig",
			Handler:    _AIService_AnalyzeConfig_Handler,
		},
		{
			MethodName: "ChatWithAI",
			Handler:    _AIService_ChatWithAI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateon/v1/ai.proto",
}
