// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: api.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\tgateon.v1\x1a\fstatus.proto\x1a\vroute.proto\x1a\rservice.proto\x1a\fglobal.proto\x1a\x10entrypoint.proto\x1a\x10middleware.proto\x1a\ttls.proto\x1a\n" +
	"auth.proto2\xc9\x0f\n" +
	"\n" +
	"ApiService\x12F\n" +
	"\tGetStatus\x12\x1b.gateon.v1.GetStatusRequest\x1a\x1c.gateon.v1.GetStatusResponse\x12I\n" +
	"\n" +
	"ListRoutes\x12\x1c.gateon.v1.ListRoutesRequest\x1a\x1d.gateon.v1.ListRoutesResponse\x12L\n" +
	"\vUpdateRoute\x12\x1d.gateon.v1.UpdateRouteRequest\x1a\x1e.gateon.v1.UpdateRouteResponse\x12L\n" +
	"\vDeleteRoute\x12\x1d.gateon.v1.DeleteRouteRequest\x1a\x1e.gateon.v1.DeleteRouteResponse\x12O\n" +
	"\fListServices\x12\x1e.gateon.v1.ListServicesRequest\x1a\x1f.gateon.v1.ListServicesResponse\x12R\n" +
	"\rUpdateService\x12\x1f.gateon.v1.UpdateServiceRequest\x1a .gateon.v1.UpdateServiceResponse\x12R\n" +
	"\rDeleteService\x12\x1f.gateon.v1.DeleteServiceRequest\x1a .gateon.v1.DeleteServiceResponse\x12M\n" +
	"\x0fGetGlobalConfig\x12!.gateon.v1.GetGlobalConfigRequest\x1a\x17.gateon.v1.GlobalConfig\x12a\n" +
	"\x12UpdateGlobalConfig\x12$.gateon.v1.UpdateGlobalConfigRequest\x1a%.gateon.v1.UpdateGlobalConfigResponse\x12X\n" +
	"\x0fListEntryPoints\x12!.gateon.v1.ListEntryPointsRequest\x1a\".gateon.v1.ListEntryPointsResponse\x12[\n" +
	"\x10UpdateEntryPoint\x12\".gateon.v1.UpdateEntryPointRequest\x1a#.gateon.v1.UpdateEntryPointResponse\x12[\n" +
	"\x10DeleteEntryPoint\x12\".gateon.v1.DeleteEntryPointRequest\x1a#.gateon.v1.DeleteEntryPointResponse\x12X\n" +
	"\x0fListMiddlewares\x12!.gateon.v1.ListMiddlewaresRequest\x1a\".gateon.v1.ListMiddlewaresResponse\x12[\n" +
	"\x10UpdateMiddleware\x12\".gateon.v1.UpdateMiddlewareRequest\x1a#.gateon.v1.UpdateMiddlewareResponse\x12[\n" +
	"\x10DeleteMiddleware\x12\".gateon.v1.DeleteMiddlewareRequest\x1a#.gateon.v1.DeleteMiddlewareResponse\x12U\n" +
	"\x0eListTLSOptions\x12 .gateon.v1.ListTLSOptionsRequest\x1a!.gateon.v1.ListTLSOptionsResponse\x12X\n" +
	"\x0fUpdateTLSOption\x12!.gateon.v1.UpdateTLSOptionRequest\x1a\".gateon.v1.UpdateTLSOptionResponse\x12X\n" +
	"\x0fDeleteTLSOption\x12!.gateon.v1.DeleteTLSOptionRequest\x1a\".gateon.v1.DeleteTLSOptionResponse\x12:\n" +
	"\x05Login\x12\x17.gateon.v1.LoginRequest\x1a\x18.gateon.v1.LoginResponse\x12X\n" +
	"\x0fIsSetupRequired\x12!.gateon.v1.IsSetupRequiredRequest\x1a\".gateon.v1.IsSetupRequiredResponse\x12:\n" +
	"\x05Setup\x12\x17.gateon.v1.SetupRequest\x1a\x18.gateon.v1.SetupResponse\x12F\n" +
	"\tListUsers\x12\x1b.gateon.v1.ListUsersRequest\x1a\x1c.gateon.v1.ListUsersResponse\x12I\n" +
	"\n" +
	"UpdateUser\x12\x1c.gateon.v1.UpdateUserRequest\x1a\x1d.gateon.v1.UpdateUserResponse\x12I\n" +
	"\n" +
	"DeleteUser\x12\x1c.gateon.v1.DeleteUserRequest\x1a\x1d.gateon.v1.DeleteUserResponseB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var file_api_proto_goTypes = []any{
	(*GetStatusRequest)(nil),           // 0: gateon.v1.GetStatusRequest
	(*ListRoutesRequest)(nil),          // 1: gateon.v1.ListRoutesRequest
	(*UpdateRouteRequest)(nil),         // 2: gateon.v1.UpdateRouteRequest
	(*DeleteRouteRequest)(nil),         // 3: gateon.v1.DeleteRouteRequest
	(*ListServicesRequest)(nil),        // 4: gateon.v1.ListServicesRequest
	(*UpdateServiceRequest)(nil),       // 5: gateon.v1.UpdateServiceRequest
	(*DeleteServiceRequest)(nil),       // 6: gateon.v1.DeleteServiceRequest
	(*GetGlobalConfigRequest)(nil),     // 7: gateon.v1.GetGlobalConfigRequest
	(*UpdateGlobalConfigRequest)(nil),  // 8: gateon.v1.UpdateGlobalConfigRequest
	(*ListEntryPointsRequest)(nil),     // 9: gateon.v1.ListEntryPointsRequest
	(*UpdateEntryPointRequest)(nil),    // 10: gateon.v1.UpdateEntryPointRequest
	(*DeleteEntryPointRequest)(nil),    // 11: gateon.v1.DeleteEntryPointRequest
	(*ListMiddlewaresRequest)(nil),     // 12: gateon.v1.ListMiddlewaresRequest
	(*UpdateMiddlewareRequest)(nil),    // 13: gateon.v1.UpdateMiddlewareRequest
	(*DeleteMiddlewareRequest)(nil),    // 14: gateon.v1.DeleteMiddlewareRequest
	(*ListTLSOptionsRequest)(nil),      // 15: gateon.v1.ListTLSOptionsRequest
	(*UpdateTLSOptionRequest)(nil),     // 16: gateon.v1.UpdateTLSOptionRequest
	(*DeleteTLSOptionRequest)(nil),     // 17: gateon.v1.DeleteTLSOptionRequest
	(*LoginRequest)(nil),               // 18: gateon.v1.LoginRequest
	(*IsSetupRequiredRequest)(nil),     // 19: gateon.v1.IsSetupRequiredRequest
	(*SetupRequest)(nil),               // 20: gateon.v1.SetupRequest
	(*ListUsersRequest)(nil),           // 21: gateon.v1.ListUsersRequest
	(*UpdateUserRequest)(nil),          // 22: gateon.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),          // 23: gateon.v1.DeleteUserRequest
	(*GetStatusResponse)(nil),          // 24: gateon.v1.GetStatusResponse
	(*ListRoutesResponse)(nil),         // 25: gateon.v1.ListRoutesResponse
	(*UpdateRouteResponse)(nil),        // 26: gateon.v1.UpdateRouteResponse
	(*DeleteRouteResponse)(nil),        // 27: gateon.v1.DeleteRouteResponse
	(*ListServicesResponse)(nil),       // 28: gateon.v1.ListServicesResponse
	(*UpdateServiceResponse)(nil),      // 29: gateon.v1.UpdateServiceResponse
	(*DeleteServiceResponse)(nil),      // 30: gateon.v1.DeleteServiceResponse
	(*GlobalConfig)(nil),               // 31: gateon.v1.GlobalConfig
	(*UpdateGlobalConfigResponse)(nil), // 32: gateon.v1.UpdateGlobalConfigResponse
	(*ListEntryPointsResponse)(nil),    // 33: gateon.v1.ListEntryPointsResponse
	(*UpdateEntryPointResponse)(nil),   // 34: gateon.v1.UpdateEntryPointResponse
	(*DeleteEntryPointResponse)(nil),   // 35: gateon.v1.DeleteEntryPointResponse
	(*ListMiddlewaresResponse)(nil),    // 36: gateon.v1.ListMiddlewaresResponse
	(*UpdateMiddlewareResponse)(nil),   // 37: gateon.v1.UpdateMiddlewareResponse
	(*DeleteMiddlewareResponse)(nil),   // 38: gateon.v1.DeleteMiddlewareResponse
	(*ListTLSOptionsResponse)(nil),     // 39: gateon.v1.ListTLSOptionsResponse
	(*UpdateTLSOptionResponse)(nil),    // 40: gateon.v1.UpdateTLSOptionResponse
	(*DeleteTLSOptionResponse)(nil),    // 41: gateon.v1.DeleteTLSOptionResponse
	(*LoginResponse)(nil),              // 42: gateon.v1.LoginResponse
	(*IsSetupRequiredResponse)(nil),    // 43: gateon.v1.IsSetupRequiredResponse
	(*SetupResponse)(nil),              // 44: gateon.v1.SetupResponse
	(*ListUsersResponse)(nil),          // 45: gateon.v1.ListUsersResponse
	(*UpdateUserResponse)(nil),         // 46: gateon.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),         // 47: gateon.v1.DeleteUserResponse
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: gateon.v1.ApiService.GetStatus:input_type -> gateon.v1.GetStatusRequest
	1,  // 1: gateon.v1.ApiService.ListRoutes:input_type -> gateon.v1.ListRoutesRequest
	2,  // 2: gateon.v1.ApiService.UpdateRoute:input_type -> gateon.v1.UpdateRouteRequest
	3,  // 3: gateon.v1.ApiService.DeleteRoute:input_type -> gateon.v1.DeleteRouteRequest
	4,  // 4: gateon.v1.ApiService.ListServices:input_type -> gateon.v1.ListServicesRequest
	5,  // 5: gateon.v1.ApiService.UpdateService:input_type -> gateon.v1.UpdateServiceRequest
	6,  // 6: gateon.v1.ApiService.DeleteService:input_type -> gateon.v1.DeleteServiceRequest
	7,  // 7: gateon.v1.ApiService.GetGlobalConfig:input_type -> gateon.v1.GetGlobalConfigRequest
	8,  // 8: gateon.v1.ApiService.UpdateGlobalConfig:input_type -> gateon.v1.UpdateGlobalConfigRequest
	9,  // 9: gateon.v1.ApiService.ListEntryPoints:input_type -> gateon.v1.ListEntryPointsRequest
	10, // 10: gateon.v1.ApiService.UpdateEntryPoint:input_type -> gateon.v1.UpdateEntryPointRequest
	11, // 11: gateon.v1.ApiService.DeleteEntryPoint:input_type -> gateon.v1.DeleteEntryPointRequest
	12, // 12: gateon.v1.ApiService.ListMiddlewares:input_type -> gateon.v1.ListMiddlewaresRequest
	13, // 13: gateon.v1.ApiService.UpdateMiddleware:input_type -> gateon.v1.UpdateMiddlewareRequest
	14, // 14: gateon.v1.ApiService.DeleteMiddleware:input_type -> gateon.v1.DeleteMiddlewareRequest
	15, // 15: gateon.v1.ApiService.ListTLSOptions:input_type -> gateon.v1.ListTLSOptionsRequest
	16, // 16: gateon.v1.ApiService.UpdateTLSOption:input_type -> gateon.v1.UpdateTLSOptionRequest
	17, // 17: gateon.v1.ApiService.DeleteTLSOption:input_type -> gateon.v1.DeleteTLSOptionRequest
	18, // 18: gateon.v1.ApiService.Login:input_type -> gateon.v1.LoginRequest
	19, // 19: gateon.v1.ApiService.IsSetupRequired:input_type -> gateon.v1.IsSetupRequiredRequest
	20, // 20: gateon.v1.ApiService.Setup:input_type -> gateon.v1.SetupRequest
	21, // 21: gateon.v1.ApiService.ListUsers:input_type -> gateon.v1.ListUsersRequest
	22, // 22: gateon.v1.ApiService.UpdateUser:input_type -> gateon.v1.UpdateUserRequest
	23, // 23: gateon.v1.ApiService.DeleteUser:input_type -> gateon.v1.DeleteUserRequest
	24, // 24: gateon.v1.ApiService.GetStatus:output_type -> gateon.v1.GetStatusResponse
	25, // 25: gateon.v1.ApiService.ListRoutes:output_type -> gateon.v1.ListRoutesResponse
	26, // 26: gateon.v1.ApiService.UpdateRoute:output_type -> gateon.v1.UpdateRouteResponse
	27, // 27: gateon.v1.ApiService.DeleteRoute:output_type -> gateon.v1.DeleteRouteResponse
	28, // 28: gateon.v1.ApiService.ListServices:output_type -> gateon.v1.ListServicesResponse
	29, // 29: gateon.v1.ApiService.UpdateService:output_type -> gateon.v1.UpdateServiceResponse
	30, // 30: gateon.v1.ApiService.DeleteService:output_type -> gateon.v1.DeleteServiceResponse
	31, // 31: gateon.v1.ApiService.GetGlobalConfig:output_type -> gateon.v1.GlobalConfig
	32, // 32: gateon.v1.ApiService.UpdateGlobalConfig:output_type -> gateon.v1.UpdateGlobalConfigResponse
	33, // 33: gateon.v1.ApiService.ListEntryPoints:output_type -> gateon.v1.ListEntryPointsResponse
	34, // 34: gateon.v1.ApiService.UpdateEntryPoint:output_type -> gateon.v1.UpdateEntryPointResponse
	35, // 35: gateon.v1.ApiService.DeleteEntryPoint:output_type -> gateon.v1.DeleteEntryPointResponse
	36, // 36: gateon.v1.ApiService.ListMiddlewares:output_type -> gateon.v1.ListMiddlewaresResponse
	37, // 37: gateon.v1.ApiService.UpdateMiddleware:output_type -> gateon.v1.UpdateMiddlewareResponse
	38, // 38: gateon.v1.ApiService.DeleteMiddleware:output_type -> gateon.v1.DeleteMiddlewareResponse
	39, // 39: gateon.v1.ApiService.ListTLSOptions:output_type -> gateon.v1.ListTLSOptionsResponse
	40, // 40: gateon.v1.ApiService.UpdateTLSOption:output_type -> gateon.v1.UpdateTLSOptionResponse
	41, // 41: gateon.v1.ApiService.DeleteTLSOption:output_type -> gateon.v1.DeleteTLSOptionResponse
	42, // 42: gateon.v1.ApiService.Login:output_type -> gateon.v1.LoginResponse
	43, // 43: gateon.v1.ApiService.IsSetupRequired:output_type -> gateon.v1.IsSetupRequiredResponse
	44, // 44: gateon.v1.ApiService.Setup:output_type -> gateon.v1.SetupResponse
	45, // 45: gateon.v1.ApiService.ListUsers:output_type -> gateon.v1.ListUsersResponse
	46, // 46: gateon.v1.ApiService.UpdateUser:output_type -> gateon.v1.UpdateUserResponse
	47, // 47: gateon.v1.ApiService.DeleteUser:output_type -> gateon.v1.DeleteUserResponse
	24, // [24:48] is the sub-list for method output_type
	0,  // [0:24] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_status_proto_init()
	file_route_proto_init()
	file_service_proto_init()
	file_global_proto_init()
	file_entrypoint_proto_init()
	file_middleware_proto_init()
	file_tls_proto_init()
	file_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
