// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: gateon/v1/api.proto

package gateonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiService_GetStatus_FullMethodName          = "/gateon.v1.ApiService/GetStatus"
	ApiService_ListRoutes_FullMethodName         = "/gateon.v1.ApiService/ListRoutes"
	ApiService_UpdateRoute_FullMethodName        = "/gateon.v1.ApiService/UpdateRoute"
	ApiService_DeleteRoute_FullMethodName        = "/gateon.v1.ApiService/DeleteRoute"
	ApiService_ListServices_FullMethodName       = "/gateon.v1.ApiService/ListServices"
	ApiService_UpdateService_FullMethodName      = "/gateon.v1.ApiService/UpdateService"
	ApiService_DeleteService_FullMethodName      = "/gateon.v1.ApiService/DeleteService"
	ApiService_GetGlobalConfig_FullMethodName    = "/gateon.v1.ApiService/GetGlobalConfig"
	ApiService_UpdateGlobalConfig_FullMethodName = "/gateon.v1.ApiService/UpdateGlobalConfig"
	ApiService_ListEntryPoints_FullMethodName    = "/gateon.v1.ApiService/ListEntryPoints"
	ApiService_UpdateEntryPoint_FullMethodName   = "/gateon.v1.ApiService/UpdateEntryPoint"
	ApiService_DeleteEntryPoint_FullMethodName   = "/gateon.v1.ApiService/DeleteEntryPoint"
	ApiService_ListMiddlewares_FullMethodName    = "/gateon.v1.ApiService/ListMiddlewares"
	ApiService_UpdateMiddleware_FullMethodName   = "/gateon.v1.ApiService/UpdateMiddleware"
	ApiService_DeleteMiddleware_FullMethodName   = "/gateon.v1.ApiService/DeleteMiddleware"
	ApiService_ListTLSOptions_FullMethodName     = "/gateon.v1.ApiService/ListTLSOptions"
	ApiService_UpdateTLSOption_FullMethodName    = "/gateon.v1.ApiService/UpdateTLSOption"
	ApiService_DeleteTLSOption_FullMethodName    = "/gateon.v1.ApiService/DeleteTLSOption"
	ApiService_Login_FullMethodName              = "/gateon.v1.ApiService/Login"
	ApiService_IsSetupRequired_FullMethodName    = "/gateon.v1.ApiService/IsSetupRequired"
	ApiService_Setup_FullMethodName              = "/gateon.v1.ApiService/Setup"
	ApiService_ListUsers_FullMethodName          = "/gateon.v1.ApiService/ListUsers"
	ApiService_UpdateUser_FullMethodName         = "/gateon.v1.ApiService/UpdateUser"
	ApiService_DeleteUser_FullMethodName         = "/gateon.v1.ApiService/DeleteUser"
)

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*UpdateServiceResponse, error)
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error)
	GetGlobalConfig(ctx context.Context, in *GetGlobalConfigRequest, opts ...grpc.CallOption) (*GlobalConfig, error)
	UpdateGlobalConfig(ctx context.Context, in *UpdateGlobalConfigRequest, opts ...grpc.CallOption) (*UpdateGlobalConfigResponse, error)
	ListEntryPoints(ctx context.Context, in *ListEntryPointsRequest, opts ...grpc.CallOption) (*ListEntryPointsResponse, error)
	UpdateEntryPoint(ctx context.Context, in *UpdateEntryPointRequest, opts ...grpc.CallOption) (*UpdateEntryPointResponse, error)
	DeleteEntryPoint(ctx context.Context, in *DeleteEntryPointRequest, opts ...grpc.CallOption) (*DeleteEntryPointResponse, error)
	ListMiddlewares(ctx context.Context, in *ListMiddlewaresRequest, opts ...grpc.CallOption) (*ListMiddlewaresResponse, error)
	UpdateMiddleware(ctx context.Context, in *UpdateMiddlewareRequest, opts ...grpc.CallOption) (*UpdateMiddlewareResponse, error)
	DeleteMiddleware(ctx context.Context, in *DeleteMiddlewareRequest, opts ...grpc.CallOption) (*DeleteMiddlewareResponse, error)
	ListTLSOptions(ctx context.Context, in *ListTLSOptionsRequest, opts ...grpc.CallOption) (*ListTLSOptionsResponse, error)
	UpdateTLSOption(ctx context.Context, in *UpdateTLSOptionRequest, opts ...grpc.CallOption) (*UpdateTLSOptionResponse, error)
	DeleteTLSOption(ctx context.Context, in *DeleteTLSOptionRequest, opts ...grpc.CallOption) (*DeleteTLSOptionResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	IsSetupRequired(ctx context.Context, in *IsSetupRequiredRequest, opts ...grpc.CallOption) (*IsSetupRequiredResponse, error)
	Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type apiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServiceClient(cc grpc.ClientConnInterface) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ApiService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, ApiService_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRouteResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, ApiService_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ApiService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*UpdateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServiceResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceResponse)
	err := c.cc.Invoke(ctx, ApiService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetGlobalConfig(ctx context.Context, in *GetGlobalConfigRequest, opts ...grpc.CallOption) (*GlobalConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalConfig)
	err := c.cc.Invoke(ctx, ApiService_GetGlobalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateGlobalConfig(ctx context.Context, in *UpdateGlobalConfigRequest, opts ...grpc.CallOption) (*UpdateGlobalConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGlobalConfigResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateGlobalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListEntryPoints(ctx context.Context, in *ListEntryPointsRequest, opts ...grpc.CallOption) (*ListEntryPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntryPointsResponse)
	err := c.cc.Invoke(ctx, ApiService_ListEntryPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateEntryPoint(ctx context.Context, in *UpdateEntryPointRequest, opts ...grpc.CallOption) (*UpdateEntryPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEntryPointResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateEntryPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteEntryPoint(ctx context.Context, in *DeleteEntryPointRequest, opts ...grpc.CallOption) (*DeleteEntryPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEntryPointResponse)
	err := c.cc.Invoke(ctx, ApiService_DeleteEntryPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListMiddlewares(ctx context.Context, in *ListMiddlewaresRequest, opts ...grpc.CallOption) (*ListMiddlewaresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMiddlewaresResponse)
	err := c.cc.Invoke(ctx, ApiService_ListMiddlewares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateMiddleware(ctx context.Context, in *UpdateMiddlewareRequest, opts ...grpc.CallOption) (*UpdateMiddlewareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMiddlewareResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateMiddleware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteMiddleware(ctx context.Context, in *DeleteMiddlewareRequest, opts ...grpc.CallOption) (*DeleteMiddlewareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMiddlewareResponse)
	err := c.cc.Invoke(ctx, ApiService_DeleteMiddleware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListTLSOptions(ctx context.Context, in *ListTLSOptionsRequest, opts ...grpc.CallOption) (*ListTLSOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTLSOptionsResponse)
	err := c.cc.Invoke(ctx, ApiService_ListTLSOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateTLSOption(ctx context.Context, in *UpdateTLSOptionRequest, opts ...grpc.CallOption) (*UpdateTLSOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTLSOptionResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateTLSOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteTLSOption(ctx context.Context, in *DeleteTLSOptionRequest, opts ...grpc.CallOption) (*DeleteTLSOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTLSOptionResponse)
	err := c.cc.Invoke(ctx, ApiService_DeleteTLSOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, ApiService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) IsSetupRequired(ctx context.Context, in *IsSetupRequiredRequest, opts ...grpc.CallOption) (*IsSetupRequiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsSetupRequiredResponse)
	err := c.cc.Invoke(ctx, ApiService_IsSetupRequired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupResponse)
	err := c.cc.Invoke(ctx, ApiService_Setup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, ApiService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, ApiService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, ApiService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
// All implementations must embed UnimplementedApiServiceServer
// for forward compatibility.
type ApiServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*UpdateServiceResponse, error)
	DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error)
	GetGlobalConfig(context.Context, *GetGlobalConfigRequest) (*GlobalConfig, error)
	UpdateGlobalConfig(context.Context, *UpdateGlobalConfigRequest) (*UpdateGlobalConfigResponse, error)
	ListEntryPoints(context.Context, *ListEntryPointsRequest) (*ListEntryPointsResponse, error)
	UpdateEntryPoint(context.Context, *UpdateEntryPointRequest) (*UpdateEntryPointResponse, error)
	DeleteEntryPoint(context.Context, *DeleteEntryPointRequest) (*DeleteEntryPointResponse, error)
	ListMiddlewares(context.Context, *ListMiddlewaresRequest) (*ListMiddlewaresResponse, error)
	UpdateMiddleware(context.Context, *UpdateMiddlewareRequest) (*UpdateMiddlewareResponse, error)
	DeleteMiddleware(context.Context, *DeleteMiddlewareRequest) (*DeleteMiddlewareResponse, error)
	ListTLSOptions(context.Context, *ListTLSOptionsRequest) (*ListTLSOptionsResponse, error)
	UpdateTLSOption(context.Context, *UpdateTLSOptionRequest) (*UpdateTLSOptionResponse, error)
	DeleteTLSOption(context.Context, *DeleteTLSOptionRequest) (*DeleteTLSOptionResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	IsSetupRequired(context.Context, *IsSetupRequiredRequest) (*IsSetupRequiredResponse, error)
	Setup(context.Context, *SetupRequest) (*SetupResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	mustEmbedUnimplementedApiServiceServer()
}

// UnimplementedApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServiceServer struct{}

func (UnimplementedApiServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedApiServiceServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedApiServiceServer) UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedApiServiceServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedApiServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedApiServiceServer) UpdateService(context.Context, *UpdateServiceRequest) (*UpdateServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedApiServiceServer) DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedApiServiceServer) GetGlobalConfig(context.Context, *GetGlobalConfigRequest) (*GlobalConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalConfig not implemented")
}
func (UnimplementedApiServiceServer) UpdateGlobalConfig(context.Context, *UpdateGlobalConfigRequest) (*UpdateGlobalConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGlobalConfig not implemented")
}
func (UnimplementedApiServiceServer) ListEntryPoints(context.Context, *ListEntryPointsRequest) (*ListEntryPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntryPoints not implemented")
}
func (UnimplementedApiServiceServer) UpdateEntryPoint(context.Context, *UpdateEntryPointRequest) (*UpdateEntryPointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEntryPoint not implemented")
}
func (UnimplementedApiServiceServer) DeleteEntryPoint(context.Context, *DeleteEntryPointRequest) (*DeleteEntryPointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEntryPoint not implemented")
}
func (UnimplementedApiServiceServer) ListMiddlewares(context.Context, *ListMiddlewaresRequest) (*ListMiddlewaresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMiddlewares not implemented")
}
func (UnimplementedApiServiceServer) UpdateMiddleware(context.Context, *UpdateMiddlewareRequest) (*UpdateMiddlewareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMiddleware not implemented")
}
func (UnimplementedApiServiceServer) DeleteMiddleware(context.Context, *DeleteMiddlewareRequest) (*DeleteMiddlewareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMiddleware not implemented")
}
func (UnimplementedApiServiceServer) ListTLSOptions(context.Context, *ListTLSOptionsRequest) (*ListTLSOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTLSOptions not implemented")
}
func (UnimplementedApiServiceServer) UpdateTLSOption(context.Context, *UpdateTLSOptionRequest) (*UpdateTLSOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTLSOption not implemented")
}
func (UnimplementedApiServiceServer) DeleteTLSOption(context.Context, *DeleteTLSOptionRequest) (*DeleteTLSOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTLSOption not implemented")
}
func (UnimplementedApiServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedApiServiceServer) IsSetupRequired(context.Context, *IsSetupRequiredRequest) (*IsSetupRequiredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsSetupRequired not implemented")
}
func (UnimplementedApiServiceServer) Setup(context.Context, *SetupRequest) (*SetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedApiServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedApiServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedApiServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedApiServiceServer) mustEmbedUnimplementedApiServiceServer() {}
func (UnimplementedApiServiceServer) testEmbeddedByValue()                    {}

// UnsafeApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServiceServer will
// result in compilation errors.
type UnsafeApiServiceServer interface {
	mustEmbedUnimplementedApiServiceServer()
}

func RegisterApiServiceServer(s grpc.ServiceRegistrar, srv ApiServiceServer) {
	// If the following call panics, it indicates UnimplementedApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiService_ServiceDesc, srv)
}

func _ApiService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateRoute(ctx, req.(*UpdateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetGlobalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_GetGlobalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetGlobalConfig(ctx, req.(*GetGlobalConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGlobalConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateGlobalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateGlobalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateGlobalConfig(ctx, req.(*UpdateGlobalConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListEntryPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntryPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListEntryPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ListEntryPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListEntryPoints(ctx, req.(*ListEntryPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateEntryPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntryPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateEntryPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateEntryPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateEntryPoint(ctx, req.(*UpdateEntryPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteEntryPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntryPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteEntryPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_DeleteEntryPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteEntryPoint(ctx, req.(*DeleteEntryPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListMiddlewares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMiddlewaresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListMiddlewares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ListMiddlewares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListMiddlewares(ctx, req.(*ListMiddlewaresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateMiddleware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateMiddleware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateMiddleware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateMiddleware(ctx, req.(*UpdateMiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteMiddleware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteMiddleware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_DeleteMiddleware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteMiddleware(ctx, req.(*DeleteMiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListTLSOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTLSOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListTLSOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ListTLSOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListTLSOptions(ctx, req.(*ListTLSOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateTLSOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTLSOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateTLSOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateTLSOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateTLSOption(ctx, req.(*UpdateTLSOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteTLSOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTLSOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteTLSOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_DeleteTLSOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteTLSOption(ctx, req.(*DeleteTLSOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_IsSetupRequired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsSetupRequiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).IsSetupRequired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_IsSetupRequired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).IsSetupRequired(ctx, req.(*IsSetupRequiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_Setup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).Setup(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiService_ServiceDesc is the grpc.ServiceDesc for ApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateon.v1.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ApiService_GetStatus_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _ApiService_ListRoutes_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _ApiService_UpdateRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _ApiService_DeleteRoute_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ApiService_ListServices_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _ApiService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ApiService_DeleteService_Handler,
		},
		{
			MethodName: "GetGlobalConfig",
			Handler:    _ApiService_GetGlobalConfig_Handler,
		},
		{
			MethodName: "UpdateGlobalConfig",
			Handler:    _ApiService_UpdateGlobalConfig_Handler,
		},
		{
			MethodName: "ListEntryPoints",
			Handler:    _ApiService_ListEntryPoints_Handler,
		},
		{
			MethodName: "UpdateEntryPoint",
			Handler:    _ApiService_UpdateEntryPoint_Handler,
		},
		{
			MethodName: "DeleteEntryPoint",
			Handler:    _ApiService_DeleteEntryPoint_Handler,
		},
		{
			MethodName: "ListMiddlewares",
			Handler:    _ApiService_ListMiddlewares_Handler,
		},
		{
			MethodName: "UpdateMiddleware",
			Handler:    _ApiService_UpdateMiddleware_Handler,
		},
		{
			MethodName: "DeleteMiddleware",
			Handler:    _ApiService_DeleteMiddleware_Handler,
		},
		{
			MethodName: "ListTLSOptions",
			Handler:    _ApiService_ListTLSOptions_Handler,
		},
		{
			MethodName: "UpdateTLSOption",
			Handler:    _ApiService_UpdateTLSOption_Handler,
		},
		{
			MethodName: "DeleteTLSOption",
			Handler:    _ApiService_DeleteTLSOption_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ApiService_Login_Handler,
		},
		{
			MethodName: "IsSetupRequired",
			Handler:    _ApiService_IsSetupRequired_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _ApiService_Setup_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _ApiService_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _ApiService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _ApiService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateon/v1/api.proto",
}
