// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/common.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`           // HTTP/gRPC: "http://host:port". L4: "host:port"
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`    // For weighted load balancing
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // HTTP/gRPC: "http", "https", "h2", "h2c". L4: unused
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_gateon_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Target) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Target) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type TlsConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Domains           []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	AutoRedirect      bool                   `protobuf:"varint,6,opt,name=auto_redirect,json=autoRedirect,proto3" json:"auto_redirect,omitempty"`
	MinTlsVersion     string                 `protobuf:"bytes,8,opt,name=min_tls_version,json=minTlsVersion,proto3" json:"min_tls_version,omitempty"` // "TLS1.0", "TLS1.1", "TLS1.2", "TLS1.3"
	MaxTlsVersion     string                 `protobuf:"bytes,9,opt,name=max_tls_version,json=maxTlsVersion,proto3" json:"max_tls_version,omitempty"`
	ClientAuthType    string                 `protobuf:"bytes,10,opt,name=client_auth_type,json=clientAuthType,proto3" json:"client_auth_type,omitempty"` // "NoClientCert", "RequestClientCert", etc.
	CipherSuites      []string               `protobuf:"bytes,11,rep,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	Certificates      []*Certificate         `protobuf:"bytes,12,rep,name=certificates,proto3" json:"certificates,omitempty"`
	ClientAuthorities []*ClientAuthority     `protobuf:"bytes,13,rep,name=client_authorities,json=clientAuthorities,proto3" json:"client_authorities,omitempty"`
	Acme              *AcmeConfig            `protobuf:"bytes,14,opt,name=acme,proto3" json:"acme,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TlsConfig) Reset() {
	*x = TlsConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsConfig) ProtoMessage() {}

func (x *TlsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsConfig.ProtoReflect.Descriptor instead.
func (*TlsConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *TlsConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TlsConfig) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TlsConfig) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *TlsConfig) GetAutoRedirect() bool {
	if x != nil {
		return x.AutoRedirect
	}
	return false
}

func (x *TlsConfig) GetMinTlsVersion() string {
	if x != nil {
		return x.MinTlsVersion
	}
	return ""
}

func (x *TlsConfig) GetMaxTlsVersion() string {
	if x != nil {
		return x.MaxTlsVersion
	}
	return ""
}

func (x *TlsConfig) GetClientAuthType() string {
	if x != nil {
		return x.ClientAuthType
	}
	return ""
}

func (x *TlsConfig) GetCipherSuites() []string {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *TlsConfig) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *TlsConfig) GetClientAuthorities() []*ClientAuthority {
	if x != nil {
		return x.ClientAuthorities
	}
	return nil
}

func (x *TlsConfig) GetAcme() *AcmeConfig {
	if x != nil {
		return x.Acme
	}
	return nil
}

type AcmeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CaServer      string                 `protobuf:"bytes,3,opt,name=ca_server,json=caServer,proto3" json:"ca_server,omitempty"`                // e.g. https://acme-v02.api.letsencrypt.org/directory
	ChallengeType string                 `protobuf:"bytes,4,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"` // "http", "tls-alpn", "dns"
	DnsProvider   string                 `protobuf:"bytes,5,opt,name=dns_provider,json=dnsProvider,proto3" json:"dns_provider,omitempty"`       // e.g. "cloudflare", "digitalocean" (for DNS-01)
	DnsConfig     map[string]string      `protobuf:"bytes,6,rep,name=dns_config,json=dnsConfig,proto3" json:"dns_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeConfig) Reset() {
	*x = AcmeConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeConfig) ProtoMessage() {}

func (x *AcmeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeConfig.ProtoReflect.Descriptor instead.
func (*AcmeConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AcmeConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AcmeConfig) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AcmeConfig) GetCaServer() string {
	if x != nil {
		return x.CaServer
	}
	return ""
}

func (x *AcmeConfig) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *AcmeConfig) GetDnsProvider() string {
	if x != nil {
		return x.DnsProvider
	}
	return ""
}

func (x *AcmeConfig) GetDnsConfig() map[string]string {
	if x != nil {
		return x.DnsConfig
	}
	return nil
}

type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CertFile      string                 `protobuf:"bytes,3,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,4,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_gateon_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Certificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Certificate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Certificate) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Certificate) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

type ClientAuthority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CaFile        string                 `protobuf:"bytes,3,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAuthority) Reset() {
	*x = ClientAuthority{}
	mi := &file_gateon_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthority) ProtoMessage() {}

func (x *ClientAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthority.ProtoReflect.Descriptor instead.
func (*ClientAuthority) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ClientAuthority) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientAuthority) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientAuthority) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

// DatabaseConfig holds structured DB connection params.
type DatabaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`                           // sqlite | postgres | mysql | mariadb
	SqlitePath    string                 `protobuf:"bytes,2,opt,name=sqlite_path,json=sqlitePath,proto3" json:"sqlite_path,omitempty"` // For sqlite only
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Database      string                 `protobuf:"bytes,7,opt,name=database,proto3" json:"database,omitempty"`
	SslMode       string                 `protobuf:"bytes,8,opt,name=ssl_mode,json=sslMode,proto3" json:"ssl_mode,omitempty"` // For postgres: disable, require, verify-full, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *DatabaseConfig) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DatabaseConfig) GetSqlitePath() string {
	if x != nil {
		return x.SqlitePath
	}
	return ""
}

func (x *DatabaseConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DatabaseConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatabaseConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatabaseConfig) GetSslMode() string {
	if x != nil {
		return x.SslMode
	}
	return ""
}

// TransportConfig tunes HTTP transport connection pooling for high-throughput backends.
type TransportConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MaxIdleConns           int32                  `protobuf:"varint,1,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxIdleConnsPerHost    int32                  `protobuf:"varint,2,opt,name=max_idle_conns_per_host,json=maxIdleConnsPerHost,proto3" json:"max_idle_conns_per_host,omitempty"`
	IdleConnTimeoutSeconds int32                  `protobuf:"varint,3,opt,name=idle_conn_timeout_seconds,json=idleConnTimeoutSeconds,proto3" json:"idle_conn_timeout_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransportConfig) Reset() {
	*x = TransportConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportConfig) ProtoMessage() {}

func (x *TransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportConfig.ProtoReflect.Descriptor instead.
func (*TransportConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *TransportConfig) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *TransportConfig) GetMaxIdleConnsPerHost() int32 {
	if x != nil {
		return x.MaxIdleConnsPerHost
	}
	return 0
}

func (x *TransportConfig) GetIdleConnTimeoutSeconds() int32 {
	if x != nil {
		return x.IdleConnTimeoutSeconds
	}
	return 0
}

type RedisConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisConfig) Reset() {
	*x = RedisConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisConfig) ProtoMessage() {}

func (x *RedisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisConfig.ProtoReflect.Descriptor instead.
func (*RedisConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *RedisConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RedisConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RedisConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisConfig) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type OtelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtelConfig) Reset() {
	*x = OtelConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtelConfig) ProtoMessage() {}

func (x *OtelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtelConfig.ProtoReflect.Descriptor instead.
func (*OtelConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *OtelConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OtelConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OtelConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type LogConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Level                  string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "debug", "info", "warn", "error"
	Development            bool                   `protobuf:"varint,2,opt,name=development,proto3" json:"development,omitempty"`
	Format                 string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // "json", "text"
	PathStatsRetentionDays int32                  `protobuf:"varint,4,opt,name=path_stats_retention_days,json=pathStatsRetentionDays,proto3" json:"path_stats_retention_days,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *LogConfig) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogConfig) GetDevelopment() bool {
	if x != nil {
		return x.Development
	}
	return false
}

func (x *LogConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LogConfig) GetPathStatsRetentionDays() int32 {
	if x != nil {
		return x.PathStatsRetentionDays
	}
	return 0
}

type TlsClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CertFile      string                 `protobuf:"bytes,2,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,3,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	CaFile        string                 `protobuf:"bytes,4,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	SkipVerify    bool                   `protobuf:"varint,5,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	ServerName    string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsClientConfig) Reset() {
	*x = TlsClientConfig{}
	mi := &file_gateon_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsClientConfig) ProtoMessage() {}

func (x *TlsClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsClientConfig.ProtoReflect.Descriptor instead.
func (*TlsClientConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *TlsClientConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TlsClientConfig) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *TlsClientConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *TlsClientConfig) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *TlsClientConfig) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *TlsClientConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

var File_gateon_v1_common_proto protoreflect.FileDescriptor

const file_gateon_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16gateon/v1/common.proto\x12\tgateon.v1\"N\n" +
	"\x06Target\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xdd\x03\n" +
	"\tTlsConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12#\n" +
	"\rauto_redirect\x18\x06 \x01(\bR\fautoRedirect\x12&\n" +
	"\x0fmin_tls_version\x18\b \x01(\tR\rminTlsVersion\x12&\n" +
	"\x0fmax_tls_version\x18\t \x01(\tR\rmaxTlsVersion\x12(\n" +
	"\x10client_auth_type\x18\n" +
	" \x01(\tR\x0eclientAuthType\x12#\n" +
	"\rcipher_suites\x18\v \x03(\tR\fcipherSuites\x12:\n" +
	"\fcertificates\x18\f \x03(\v2\x16.gateon.v1.CertificateR\fcertificates\x12I\n" +
	"\x12client_authorities\x18\r \x03(\v2\x1a.gateon.v1.ClientAuthorityR\x11clientAuthorities\x12)\n" +
	"\x04acme\x18\x0e \x01(\v2\x15.gateon.v1.AcmeConfigR\x04acmeJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\a\x10\b\"\xa6\x02\n" +
	"\n" +
	"AcmeConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tca_server\x18\x03 \x01(\tR\bcaServer\x12%\n" +
	"\x0echallenge_type\x18\x04 \x01(\tR\rchallengeType\x12!\n" +
	"\fdns_provider\x18\x05 \x01(\tR\vdnsProvider\x12C\n" +
	"\n" +
	"dns_config\x18\x06 \x03(\v2$.gateon.v1.AcmeConfig.DnsConfigEntryR\tdnsConfig\x1a<\n" +
	"\x0eDnsConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcert_file\x18\x03 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x04 \x01(\tR\akeyFile\"N\n" +
	"\x0fClientAuthority\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aca_file\x18\x03 \x01(\tR\x06caFile\"\xd8\x01\n" +
	"\x0eDatabaseConfig\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x1f\n" +
	"\vsqlite_path\x18\x02 \x01(\tR\n" +
	"sqlitePath\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\a \x01(\tR\bdatabase\x12\x19\n" +
	"\bssl_mode\x18\b \x01(\tR\asslMode\"\xa8\x01\n" +
	"\x0fTransportConfig\x12$\n" +
	"\x0emax_idle_conns\x18\x01 \x01(\x05R\fmaxIdleConns\x124\n" +
	"\x17max_idle_conns_per_host\x18\x02 \x01(\x05R\x13maxIdleConnsPerHost\x129\n" +
	"\x19idle_conn_timeout_seconds\x18\x03 \x01(\x05R\x16idleConnTimeoutSeconds\"g\n" +
	"\vRedisConfig\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"e\n" +
	"\n" +
	"OtelConfig\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"\x96\x01\n" +
	"\tLogConfig\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12 \n" +
	"\vdevelopment\x18\x02 \x01(\bR\vdevelopment\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x129\n" +
	"\x19path_stats_retention_days\x18\x04 \x01(\x05R\x16pathStatsRetentionDays\"\xbe\x01\n" +
	"\x0fTlsClientConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tcert_file\x18\x02 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x03 \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\x04 \x01(\tR\x06caFile\x12\x1f\n" +
	"\vskip_verify\x18\x05 \x01(\bR\n" +
	"skipVerify\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverNameB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_common_proto_rawDescOnce sync.Once
	file_gateon_v1_common_proto_rawDescData []byte
)

func file_gateon_v1_common_proto_rawDescGZIP() []byte {
	file_gateon_v1_common_proto_rawDescOnce.Do(func() {
		file_gateon_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_common_proto_rawDesc), len(file_gateon_v1_common_proto_rawDesc)))
	})
	return file_gateon_v1_common_proto_rawDescData
}

var file_gateon_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gateon_v1_common_proto_goTypes = []any{
	(*Target)(nil),          // 0: gateon.v1.Target
	(*TlsConfig)(nil),       // 1: gateon.v1.TlsConfig
	(*AcmeConfig)(nil),      // 2: gateon.v1.AcmeConfig
	(*Certificate)(nil),     // 3: gateon.v1.Certificate
	(*ClientAuthority)(nil), // 4: gateon.v1.ClientAuthority
	(*DatabaseConfig)(nil),  // 5: gateon.v1.DatabaseConfig
	(*TransportConfig)(nil), // 6: gateon.v1.TransportConfig
	(*RedisConfig)(nil),     // 7: gateon.v1.RedisConfig
	(*OtelConfig)(nil),      // 8: gateon.v1.OtelConfig
	(*LogConfig)(nil),       // 9: gateon.v1.LogConfig
	(*TlsClientConfig)(nil), // 10: gateon.v1.TlsClientConfig
	nil,                     // 11: gateon.v1.AcmeConfig.DnsConfigEntry
}
var file_gateon_v1_common_proto_depIdxs = []int32{
	3,  // 0: gateon.v1.TlsConfig.certificates:type_name -> gateon.v1.Certificate
	4,  // 1: gateon.v1.TlsConfig.client_authorities:type_name -> gateon.v1.ClientAuthority
	2,  // 2: gateon.v1.TlsConfig.acme:type_name -> gateon.v1.AcmeConfig
	11, // 3: gateon.v1.AcmeConfig.dns_config:type_name -> gateon.v1.AcmeConfig.DnsConfigEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gateon_v1_common_proto_init() }
func file_gateon_v1_common_proto_init() {
	if File_gateon_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_common_proto_rawDesc), len(file_gateon_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateon_v1_common_proto_goTypes,
		DependencyIndexes: file_gateon_v1_common_proto_depIdxs,
		MessageInfos:      file_gateon_v1_common_proto_msgTypes,
	}.Build()
	File_gateon_v1_common_proto = out.File
	file_gateon_v1_common_proto_goTypes = nil
	file_gateon_v1_common_proto_depIdxs = nil
}
