// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: entrypoint.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryPoint_Type int32

const (
	EntryPoint_HTTP  EntryPoint_Type = 0
	EntryPoint_GRPC  EntryPoint_Type = 1
	EntryPoint_TCP   EntryPoint_Type = 2
	EntryPoint_UDP   EntryPoint_Type = 3
	EntryPoint_HTTP2 EntryPoint_Type = 4
	EntryPoint_HTTP3 EntryPoint_Type = 5
)

// Enum value maps for EntryPoint_Type.
var (
	EntryPoint_Type_name = map[int32]string{
		0: "HTTP",
		1: "GRPC",
		2: "TCP",
		3: "UDP",
		4: "HTTP2",
		5: "HTTP3",
	}
	EntryPoint_Type_value = map[string]int32{
		"HTTP":  0,
		"GRPC":  1,
		"TCP":   2,
		"UDP":   3,
		"HTTP2": 4,
		"HTTP3": 5,
	}
)

func (x EntryPoint_Type) Enum() *EntryPoint_Type {
	p := new(EntryPoint_Type)
	*p = x
	return p
}

func (x EntryPoint_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryPoint_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_entrypoint_proto_enumTypes[0].Descriptor()
}

func (EntryPoint_Type) Type() protoreflect.EnumType {
	return &file_entrypoint_proto_enumTypes[0]
}

func (x EntryPoint_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryPoint_Type.Descriptor instead.
func (EntryPoint_Type) EnumDescriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{6, 0}
}

type EntryPoint_Protocol int32

const (
	EntryPoint_TCP_PROTO EntryPoint_Protocol = 0
	EntryPoint_UDP_PROTO EntryPoint_Protocol = 1
)

// Enum value maps for EntryPoint_Protocol.
var (
	EntryPoint_Protocol_name = map[int32]string{
		0: "TCP_PROTO",
		1: "UDP_PROTO",
	}
	EntryPoint_Protocol_value = map[string]int32{
		"TCP_PROTO": 0,
		"UDP_PROTO": 1,
	}
)

func (x EntryPoint_Protocol) Enum() *EntryPoint_Protocol {
	p := new(EntryPoint_Protocol)
	*p = x
	return p
}

func (x EntryPoint_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryPoint_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_entrypoint_proto_enumTypes[1].Descriptor()
}

func (EntryPoint_Protocol) Type() protoreflect.EnumType {
	return &file_entrypoint_proto_enumTypes[1]
}

func (x EntryPoint_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryPoint_Protocol.Descriptor instead.
func (EntryPoint_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{6, 1}
}

type ListEntryPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntryPointsRequest) Reset() {
	*x = ListEntryPointsRequest{}
	mi := &file_entrypoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntryPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntryPointsRequest) ProtoMessage() {}

func (x *ListEntryPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntryPointsRequest.ProtoReflect.Descriptor instead.
func (*ListEntryPointsRequest) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{0}
}

func (x *ListEntryPointsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEntryPointsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEntryPointsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListEntryPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryPoints   []*EntryPoint          `protobuf:"bytes,1,rep,name=entry_points,json=entryPoints,proto3" json:"entry_points,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntryPointsResponse) Reset() {
	*x = ListEntryPointsResponse{}
	mi := &file_entrypoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntryPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntryPointsResponse) ProtoMessage() {}

func (x *ListEntryPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntryPointsResponse.ProtoReflect.Descriptor instead.
func (*ListEntryPointsResponse) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{1}
}

func (x *ListEntryPointsResponse) GetEntryPoints() []*EntryPoint {
	if x != nil {
		return x.EntryPoints
	}
	return nil
}

func (x *ListEntryPointsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListEntryPointsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEntryPointsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateEntryPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryPoint    *EntryPoint            `protobuf:"bytes,1,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryPointRequest) Reset() {
	*x = UpdateEntryPointRequest{}
	mi := &file_entrypoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryPointRequest) ProtoMessage() {}

func (x *UpdateEntryPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntryPointRequest) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEntryPointRequest) GetEntryPoint() *EntryPoint {
	if x != nil {
		return x.EntryPoint
	}
	return nil
}

type UpdateEntryPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryPointResponse) Reset() {
	*x = UpdateEntryPointResponse{}
	mi := &file_entrypoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryPointResponse) ProtoMessage() {}

func (x *UpdateEntryPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryPointResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntryPointResponse) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEntryPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteEntryPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryPointRequest) Reset() {
	*x = DeleteEntryPointRequest{}
	mi := &file_entrypoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryPointRequest) ProtoMessage() {}

func (x *DeleteEntryPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryPointRequest) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEntryPointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEntryPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryPointResponse) Reset() {
	*x = DeleteEntryPointResponse{}
	mi := &file_entrypoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryPointResponse) ProtoMessage() {}

func (x *DeleteEntryPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryPointResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryPointResponse) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEntryPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EntryPoint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // e.g., ":80", "0.0.0.0:443"
	Type             EntryPoint_Type        `protobuf:"varint,4,opt,name=type,proto3,enum=gateon.v1.EntryPoint_Type" json:"type,omitempty"`
	Protocol         EntryPoint_Protocol    `protobuf:"varint,11,opt,name=protocol,proto3,enum=gateon.v1.EntryPoint_Protocol" json:"protocol,omitempty"`
	Protocols        []EntryPoint_Protocol  `protobuf:"varint,12,rep,packed,name=protocols,proto3,enum=gateon.v1.EntryPoint_Protocol" json:"protocols,omitempty"`
	Tls              *TlsConfig             `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	ReadTimeoutMs    int32                  `protobuf:"varint,7,opt,name=read_timeout_ms,json=readTimeoutMs,proto3" json:"read_timeout_ms,omitempty"`
	WriteTimeoutMs   int32                  `protobuf:"varint,8,opt,name=write_timeout_ms,json=writeTimeoutMs,proto3" json:"write_timeout_ms,omitempty"`
	MaxConnections   int32                  `protobuf:"varint,9,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	AccessLogEnabled bool                   `protobuf:"varint,10,opt,name=access_log_enabled,json=accessLogEnabled,proto3" json:"access_log_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EntryPoint) Reset() {
	*x = EntryPoint{}
	mi := &file_entrypoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryPoint) ProtoMessage() {}

func (x *EntryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryPoint.ProtoReflect.Descriptor instead.
func (*EntryPoint) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{6}
}

func (x *EntryPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntryPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntryPoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EntryPoint) GetType() EntryPoint_Type {
	if x != nil {
		return x.Type
	}
	return EntryPoint_HTTP
}

func (x *EntryPoint) GetProtocol() EntryPoint_Protocol {
	if x != nil {
		return x.Protocol
	}
	return EntryPoint_TCP_PROTO
}

func (x *EntryPoint) GetProtocols() []EntryPoint_Protocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *EntryPoint) GetTls() *TlsConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *EntryPoint) GetReadTimeoutMs() int32 {
	if x != nil {
		return x.ReadTimeoutMs
	}
	return 0
}

func (x *EntryPoint) GetWriteTimeoutMs() int32 {
	if x != nil {
		return x.WriteTimeoutMs
	}
	return 0
}

func (x *EntryPoint) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *EntryPoint) GetAccessLogEnabled() bool {
	if x != nil {
		return x.AccessLogEnabled
	}
	return false
}

var File_entrypoint_proto protoreflect.FileDescriptor

const file_entrypoint_proto_rawDesc = "" +
	"\n" +
	"\x10entrypoint.proto\x12\tgateon.v1\x1a\fcommon.proto\"a\n" +
	"\x16ListEntryPointsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xa5\x01\n" +
	"\x17ListEntryPointsResponse\x128\n" +
	"\fentry_points\x18\x01 \x03(\v2\x15.gateon.v1.EntryPointR\ventryPoints\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"Q\n" +
	"\x17UpdateEntryPointRequest\x126\n" +
	"\ventry_point\x18\x01 \x01(\v2\x15.gateon.v1.EntryPointR\n" +
	"entryPoint\"4\n" +
	"\x18UpdateEntryPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x17DeleteEntryPointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteEntryPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb3\x04\n" +
	"\n" +
	"EntryPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.gateon.v1.EntryPoint.TypeR\x04type\x12:\n" +
	"\bprotocol\x18\v \x01(\x0e2\x1e.gateon.v1.EntryPoint.ProtocolR\bprotocol\x12<\n" +
	"\tprotocols\x18\f \x03(\x0e2\x1e.gateon.v1.EntryPoint.ProtocolR\tprotocols\x12&\n" +
	"\x03tls\x18\x05 \x01(\v2\x14.gateon.v1.TlsConfigR\x03tls\x12&\n" +
	"\x0fread_timeout_ms\x18\a \x01(\x05R\rreadTimeoutMs\x12(\n" +
	"\x10write_timeout_ms\x18\b \x01(\x05R\x0ewriteTimeoutMs\x12'\n" +
	"\x0fmax_connections\x18\t \x01(\x05R\x0emaxConnections\x12,\n" +
	"\x12access_log_enabled\x18\n" +
	" \x01(\bR\x10accessLogEnabled\"B\n" +
	"\x04Type\x12\b\n" +
	"\x04HTTP\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02\x12\a\n" +
	"\x03UDP\x10\x03\x12\t\n" +
	"\x05HTTP2\x10\x04\x12\t\n" +
	"\x05HTTP3\x10\x05\"(\n" +
	"\bProtocol\x12\r\n" +
	"\tTCP_PROTO\x10\x00\x12\r\n" +
	"\tUDP_PROTO\x10\x01B3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_entrypoint_proto_rawDescOnce sync.Once
	file_entrypoint_proto_rawDescData []byte
)

func file_entrypoint_proto_rawDescGZIP() []byte {
	file_entrypoint_proto_rawDescOnce.Do(func() {
		file_entrypoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entrypoint_proto_rawDesc), len(file_entrypoint_proto_rawDesc)))
	})
	return file_entrypoint_proto_rawDescData
}

var file_entrypoint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_entrypoint_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_entrypoint_proto_goTypes = []any{
	(EntryPoint_Type)(0),             // 0: gateon.v1.EntryPoint.Type
	(EntryPoint_Protocol)(0),         // 1: gateon.v1.EntryPoint.Protocol
	(*ListEntryPointsRequest)(nil),   // 2: gateon.v1.ListEntryPointsRequest
	(*ListEntryPointsResponse)(nil),  // 3: gateon.v1.ListEntryPointsResponse
	(*UpdateEntryPointRequest)(nil),  // 4: gateon.v1.UpdateEntryPointRequest
	(*UpdateEntryPointResponse)(nil), // 5: gateon.v1.UpdateEntryPointResponse
	(*DeleteEntryPointRequest)(nil),  // 6: gateon.v1.DeleteEntryPointRequest
	(*DeleteEntryPointResponse)(nil), // 7: gateon.v1.DeleteEntryPointResponse
	(*EntryPoint)(nil),               // 8: gateon.v1.EntryPoint
	(*TlsConfig)(nil),                // 9: gateon.v1.TlsConfig
}
var file_entrypoint_proto_depIdxs = []int32{
	8, // 0: gateon.v1.ListEntryPointsResponse.entry_points:type_name -> gateon.v1.EntryPoint
	8, // 1: gateon.v1.UpdateEntryPointRequest.entry_point:type_name -> gateon.v1.EntryPoint
	0, // 2: gateon.v1.EntryPoint.type:type_name -> gateon.v1.EntryPoint.Type
	1, // 3: gateon.v1.EntryPoint.protocol:type_name -> gateon.v1.EntryPoint.Protocol
	1, // 4: gateon.v1.EntryPoint.protocols:type_name -> gateon.v1.EntryPoint.Protocol
	9, // 5: gateon.v1.EntryPoint.tls:type_name -> gateon.v1.TlsConfig
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_entrypoint_proto_init() }
func file_entrypoint_proto_init() {
	if File_entrypoint_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entrypoint_proto_rawDesc), len(file_entrypoint_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entrypoint_proto_goTypes,
		DependencyIndexes: file_entrypoint_proto_depIdxs,
		EnumInfos:         file_entrypoint_proto_enumTypes,
		MessageInfos:      file_entrypoint_proto_msgTypes,
	}.Build()
	File_entrypoint_proto = out.File
	file_entrypoint_proto_goTypes = nil
	file_entrypoint_proto_depIdxs = nil
}
