// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: global.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGlobalConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalConfigRequest) Reset() {
	*x = GetGlobalConfigRequest{}
	mi := &file_global_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalConfigRequest) ProtoMessage() {}

func (x *GetGlobalConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalConfigRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalConfigRequest) Descriptor() ([]byte, []int) {
	return file_global_proto_rawDescGZIP(), []int{0}
}

type UpdateGlobalConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *GlobalConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalConfigRequest) Reset() {
	*x = UpdateGlobalConfigRequest{}
	mi := &file_global_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalConfigRequest) ProtoMessage() {}

func (x *UpdateGlobalConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_global_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalConfigRequest) Descriptor() ([]byte, []int) {
	return file_global_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateGlobalConfigRequest) GetConfig() *GlobalConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateGlobalConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalConfigResponse) Reset() {
	*x = UpdateGlobalConfigResponse{}
	mi := &file_global_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalConfigResponse) ProtoMessage() {}

func (x *UpdateGlobalConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_global_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateGlobalConfigResponse) Descriptor() ([]byte, []int) {
	return file_global_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateGlobalConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GlobalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tls           *TlsConfig             `protobuf:"bytes,1,opt,name=tls,proto3" json:"tls,omitempty"`
	Redis         *RedisConfig           `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Otel          *OtelConfig            `protobuf:"bytes,3,opt,name=otel,proto3" json:"otel,omitempty"`
	Log           *LogConfig             `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	Auth          *AuthConfig            `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	Transport     *TransportConfig       `protobuf:"bytes,6,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_global_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_global_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_global_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalConfig) GetTls() *TlsConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *GlobalConfig) GetRedis() *RedisConfig {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *GlobalConfig) GetOtel() *OtelConfig {
	if x != nil {
		return x.Otel
	}
	return nil
}

func (x *GlobalConfig) GetLog() *LogConfig {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *GlobalConfig) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *GlobalConfig) GetTransport() *TransportConfig {
	if x != nil {
		return x.Transport
	}
	return nil
}

type AuthConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PasetoSecret   string                 `protobuf:"bytes,2,opt,name=paseto_secret,json=pasetoSecret,proto3" json:"paseto_secret,omitempty"`
	SqlitePath     string                 `protobuf:"bytes,3,opt,name=sqlite_path,json=sqlitePath,proto3" json:"sqlite_path,omitempty"`    // Deprecated: use database_config or database_url
	DatabaseUrl    string                 `protobuf:"bytes,4,opt,name=database_url,json=databaseUrl,proto3" json:"database_url,omitempty"` // Fallback: sqlite:path, postgres://..., mysql://...
	DatabaseConfig *DatabaseConfig        `protobuf:"bytes,5,opt,name=database_config,json=databaseConfig,proto3" json:"database_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_global_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_global_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_global_proto_rawDescGZIP(), []int{4}
}

func (x *AuthConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AuthConfig) GetPasetoSecret() string {
	if x != nil {
		return x.PasetoSecret
	}
	return ""
}

func (x *AuthConfig) GetSqlitePath() string {
	if x != nil {
		return x.SqlitePath
	}
	return ""
}

func (x *AuthConfig) GetDatabaseUrl() string {
	if x != nil {
		return x.DatabaseUrl
	}
	return ""
}

func (x *AuthConfig) GetDatabaseConfig() *DatabaseConfig {
	if x != nil {
		return x.DatabaseConfig
	}
	return nil
}

var File_global_proto protoreflect.FileDescriptor

const file_global_proto_rawDesc = "" +
	"\n" +
	"\fglobal.proto\x12\tgateon.v1\x1a\fcommon.proto\"\x18\n" +
	"\x16GetGlobalConfigRequest\"L\n" +
	"\x19UpdateGlobalConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.gateon.v1.GlobalConfigR\x06config\"6\n" +
	"\x1aUpdateGlobalConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9c\x02\n" +
	"\fGlobalConfig\x12&\n" +
	"\x03tls\x18\x01 \x01(\v2\x14.gateon.v1.TlsConfigR\x03tls\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.gateon.v1.RedisConfigR\x05redis\x12)\n" +
	"\x04otel\x18\x03 \x01(\v2\x15.gateon.v1.OtelConfigR\x04otel\x12&\n" +
	"\x03log\x18\x04 \x01(\v2\x14.gateon.v1.LogConfigR\x03log\x12)\n" +
	"\x04auth\x18\x05 \x01(\v2\x15.gateon.v1.AuthConfigR\x04auth\x128\n" +
	"\ttransport\x18\x06 \x01(\v2\x1a.gateon.v1.TransportConfigR\ttransport\"\xd3\x01\n" +
	"\n" +
	"AuthConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rpaseto_secret\x18\x02 \x01(\tR\fpasetoSecret\x12\x1f\n" +
	"\vsqlite_path\x18\x03 \x01(\tR\n" +
	"sqlitePath\x12!\n" +
	"\fdatabase_url\x18\x04 \x01(\tR\vdatabaseUrl\x12B\n" +
	"\x0fdatabase_config\x18\x05 \x01(\v2\x19.gateon.v1.DatabaseConfigR\x0edatabaseConfigB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_global_proto_rawDescOnce sync.Once
	file_global_proto_rawDescData []byte
)

func file_global_proto_rawDescGZIP() []byte {
	file_global_proto_rawDescOnce.Do(func() {
		file_global_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_global_proto_rawDesc), len(file_global_proto_rawDesc)))
	})
	return file_global_proto_rawDescData
}

var file_global_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_global_proto_goTypes = []any{
	(*GetGlobalConfigRequest)(nil),     // 0: gateon.v1.GetGlobalConfigRequest
	(*UpdateGlobalConfigRequest)(nil),  // 1: gateon.v1.UpdateGlobalConfigRequest
	(*UpdateGlobalConfigResponse)(nil), // 2: gateon.v1.UpdateGlobalConfigResponse
	(*GlobalConfig)(nil),               // 3: gateon.v1.GlobalConfig
	(*AuthConfig)(nil),                 // 4: gateon.v1.AuthConfig
	(*TlsConfig)(nil),                  // 5: gateon.v1.TlsConfig
	(*RedisConfig)(nil),                // 6: gateon.v1.RedisConfig
	(*OtelConfig)(nil),                 // 7: gateon.v1.OtelConfig
	(*LogConfig)(nil),                  // 8: gateon.v1.LogConfig
	(*TransportConfig)(nil),            // 9: gateon.v1.TransportConfig
	(*DatabaseConfig)(nil),             // 10: gateon.v1.DatabaseConfig
}
var file_global_proto_depIdxs = []int32{
	3,  // 0: gateon.v1.UpdateGlobalConfigRequest.config:type_name -> gateon.v1.GlobalConfig
	5,  // 1: gateon.v1.GlobalConfig.tls:type_name -> gateon.v1.TlsConfig
	6,  // 2: gateon.v1.GlobalConfig.redis:type_name -> gateon.v1.RedisConfig
	7,  // 3: gateon.v1.GlobalConfig.otel:type_name -> gateon.v1.OtelConfig
	8,  // 4: gateon.v1.GlobalConfig.log:type_name -> gateon.v1.LogConfig
	4,  // 5: gateon.v1.GlobalConfig.auth:type_name -> gateon.v1.AuthConfig
	9,  // 6: gateon.v1.GlobalConfig.transport:type_name -> gateon.v1.TransportConfig
	10, // 7: gateon.v1.AuthConfig.database_config:type_name -> gateon.v1.DatabaseConfig
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_global_proto_init() }
func file_global_proto_init() {
	if File_global_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_global_proto_rawDesc), len(file_global_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_proto_goTypes,
		DependencyIndexes: file_global_proto_depIdxs,
		MessageInfos:      file_global_proto_msgTypes,
	}.Build()
	File_global_proto = out.File
	file_global_proto_goTypes = nil
	file_global_proto_depIdxs = nil
}
