// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/middleware.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMiddlewaresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMiddlewaresRequest) Reset() {
	*x = ListMiddlewaresRequest{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMiddlewaresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMiddlewaresRequest) ProtoMessage() {}

func (x *ListMiddlewaresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMiddlewaresRequest.ProtoReflect.Descriptor instead.
func (*ListMiddlewaresRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *ListMiddlewaresRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMiddlewaresRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMiddlewaresRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListMiddlewaresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middlewares   []*Middleware          `protobuf:"bytes,1,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMiddlewaresResponse) Reset() {
	*x = ListMiddlewaresResponse{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMiddlewaresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMiddlewaresResponse) ProtoMessage() {}

func (x *ListMiddlewaresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMiddlewaresResponse.ProtoReflect.Descriptor instead.
func (*ListMiddlewaresResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *ListMiddlewaresResponse) GetMiddlewares() []*Middleware {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *ListMiddlewaresResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMiddlewaresResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMiddlewaresResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateMiddlewareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middleware    *Middleware            `protobuf:"bytes,1,opt,name=middleware,proto3" json:"middleware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMiddlewareRequest) Reset() {
	*x = UpdateMiddlewareRequest{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMiddlewareRequest) ProtoMessage() {}

func (x *UpdateMiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMiddlewareRequest.ProtoReflect.Descriptor instead.
func (*UpdateMiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMiddlewareRequest) GetMiddleware() *Middleware {
	if x != nil {
		return x.Middleware
	}
	return nil
}

type UpdateMiddlewareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMiddlewareResponse) Reset() {
	*x = UpdateMiddlewareResponse{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMiddlewareResponse) ProtoMessage() {}

func (x *UpdateMiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMiddlewareResponse.ProtoReflect.Descriptor instead.
func (*UpdateMiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMiddlewareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteMiddlewareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMiddlewareRequest) Reset() {
	*x = DeleteMiddlewareRequest{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMiddlewareRequest) ProtoMessage() {}

func (x *DeleteMiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMiddlewareRequest.ProtoReflect.Descriptor instead.
func (*DeleteMiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMiddlewareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMiddlewareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMiddlewareResponse) Reset() {
	*x = DeleteMiddlewareResponse{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMiddlewareResponse) ProtoMessage() {}

func (x *DeleteMiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMiddlewareResponse.ProtoReflect.Descriptor instead.
func (*DeleteMiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMiddlewareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Supported types: ratelimit, inflightreq, buffering, auth, headers, rewrite,
// addprefix, stripprefix, stripprefixregex, replacepath, replacepathregex,
// compress, forwardauth, accesslog, metrics, errors, retry, cors, grpcweb,
// ipfilter, waf, turnstile, geoip, hmac, cache
type Middleware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WasmBlob      []byte                 `protobuf:"bytes,5,opt,name=wasm_blob,json=wasmBlob,proto3" json:"wasm_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Middleware) Reset() {
	*x = Middleware{}
	mi := &file_gateon_v1_middleware_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middleware) ProtoMessage() {}

func (x *Middleware) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_middleware_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middleware.ProtoReflect.Descriptor instead.
func (*Middleware) Descriptor() ([]byte, []int) {
	return file_gateon_v1_middleware_proto_rawDescGZIP(), []int{6}
}

func (x *Middleware) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Middleware) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Middleware) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Middleware) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Middleware) GetWasmBlob() []byte {
	if x != nil {
		return x.WasmBlob
	}
	return nil
}

var File_gateon_v1_middleware_proto protoreflect.FileDescriptor

const file_gateon_v1_middleware_proto_rawDesc = "" +
	"\n" +
	"\x1agateon/v1/middleware.proto\x12\tgateon.v1\"a\n" +
	"\x16ListMiddlewaresRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xa4\x01\n" +
	"\x17ListMiddlewaresResponse\x127\n" +
	"\vmiddlewares\x18\x01 \x03(\v2\x15.gateon.v1.MiddlewareR\vmiddlewares\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"P\n" +
	"\x17UpdateMiddlewareRequest\x125\n" +
	"\n" +
	"middleware\x18\x01 \x01(\v2\x15.gateon.v1.MiddlewareR\n" +
	"middleware\"4\n" +
	"\x18UpdateMiddlewareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x17DeleteMiddlewareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteMiddlewareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd7\x01\n" +
	"\n" +
	"Middleware\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\x06config\x18\x04 \x03(\v2!.gateon.v1.Middleware.ConfigEntryR\x06config\x12\x1b\n" +
	"\twasm_blob\x18\x05 \x01(\fR\bwasmBlob\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_middleware_proto_rawDescOnce sync.Once
	file_gateon_v1_middleware_proto_rawDescData []byte
)

func file_gateon_v1_middleware_proto_rawDescGZIP() []byte {
	file_gateon_v1_middleware_proto_rawDescOnce.Do(func() {
		file_gateon_v1_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_middleware_proto_rawDesc), len(file_gateon_v1_middleware_proto_rawDesc)))
	})
	return file_gateon_v1_middleware_proto_rawDescData
}

var file_gateon_v1_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateon_v1_middleware_proto_goTypes = []any{
	(*ListMiddlewaresRequest)(nil),   // 0: gateon.v1.ListMiddlewaresRequest
	(*ListMiddlewaresResponse)(nil),  // 1: gateon.v1.ListMiddlewaresResponse
	(*UpdateMiddlewareRequest)(nil),  // 2: gateon.v1.UpdateMiddlewareRequest
	(*UpdateMiddlewareResponse)(nil), // 3: gateon.v1.UpdateMiddlewareResponse
	(*DeleteMiddlewareRequest)(nil),  // 4: gateon.v1.DeleteMiddlewareRequest
	(*DeleteMiddlewareResponse)(nil), // 5: gateon.v1.DeleteMiddlewareResponse
	(*Middleware)(nil),               // 6: gateon.v1.Middleware
	nil,                              // 7: gateon.v1.Middleware.ConfigEntry
}
var file_gateon_v1_middleware_proto_depIdxs = []int32{
	6, // 0: gateon.v1.ListMiddlewaresResponse.middlewares:type_name -> gateon.v1.Middleware
	6, // 1: gateon.v1.UpdateMiddlewareRequest.middleware:type_name -> gateon.v1.Middleware
	7, // 2: gateon.v1.Middleware.config:type_name -> gateon.v1.Middleware.ConfigEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateon_v1_middleware_proto_init() }
func file_gateon_v1_middleware_proto_init() {
	if File_gateon_v1_middleware_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_middleware_proto_rawDesc), len(file_gateon_v1_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateon_v1_middleware_proto_goTypes,
		DependencyIndexes: file_gateon_v1_middleware_proto_depIdxs,
		MessageInfos:      file_gateon_v1_middleware_proto_msgTypes,
	}.Build()
	File_gateon_v1_middleware_proto = out.File
	file_gateon_v1_middleware_proto_goTypes = nil
	file_gateon_v1_middleware_proto_depIdxs = nil
}
