// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/route.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_gateon_v1_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *ListRoutesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRoutesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoutesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_gateon_v1_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{1}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ListRoutesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListRoutesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRoutesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteRequest) Reset() {
	*x = UpdateRouteRequest{}
	mi := &file_gateon_v1_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteRequest) ProtoMessage() {}

func (x *UpdateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type UpdateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteResponse) Reset() {
	*x = UpdateRouteResponse{}
	mi := &file_gateon_v1_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteResponse) ProtoMessage() {}

func (x *UpdateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouteResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_gateon_v1_route_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRouteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_gateon_v1_route_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "http", "grpc", "graphql", "tcp", "udp"
	Entrypoints   []string               `protobuf:"bytes,4,rep,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	Rule          string                 `protobuf:"bytes,5,opt,name=rule,proto3" json:"rule,omitempty"` // For L4 routes use "L4()" (matching by entrypoint only)
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Middlewares   []string               `protobuf:"bytes,7,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	ServiceId     string                 `protobuf:"bytes,8,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Tls           *RouteTLSConfig        `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	Disabled      bool                   `protobuf:"varint,10,opt,name=disabled,proto3" json:"disabled,omitempty"` // When true, route is not matched (paused)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_gateon_v1_route_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{6}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Route) GetEntrypoints() []string {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *Route) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Route) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Route) GetMiddlewares() []string {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *Route) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Route) GetTls() *RouteTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Route) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RouteTLSConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificateIds []string               `protobuf:"bytes,1,rep,name=certificate_ids,json=certificateIds,proto3" json:"certificate_ids,omitempty"`
	OptionId       string                 `protobuf:"bytes,2,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteTLSConfig) Reset() {
	*x = RouteTLSConfig{}
	mi := &file_gateon_v1_route_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTLSConfig) ProtoMessage() {}

func (x *RouteTLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_route_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTLSConfig.ProtoReflect.Descriptor instead.
func (*RouteTLSConfig) Descriptor() ([]byte, []int) {
	return file_gateon_v1_route_proto_rawDescGZIP(), []int{7}
}

func (x *RouteTLSConfig) GetCertificateIds() []string {
	if x != nil {
		return x.CertificateIds
	}
	return nil
}

func (x *RouteTLSConfig) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

var File_gateon_v1_route_proto protoreflect.FileDescriptor

const file_gateon_v1_route_proto_rawDesc = "" +
	"\n" +
	"\x15gateon/v1/route.proto\x12\tgateon.v1\"\\\n" +
	"\x11ListRoutesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x90\x01\n" +
	"\x12ListRoutesResponse\x12(\n" +
	"\x06routes\x18\x01 \x03(\v2\x10.gateon.v1.RouteR\x06routes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"<\n" +
	"\x12UpdateRouteRequest\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.gateon.v1.RouteR\x05route\"/\n" +
	"\x13UpdateRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12DeleteRouteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9b\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\ventrypoints\x18\x04 \x03(\tR\ventrypoints\x12\x12\n" +
	"\x04rule\x18\x05 \x01(\tR\x04rule\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12 \n" +
	"\vmiddlewares\x18\a \x03(\tR\vmiddlewares\x12\x1d\n" +
	"\n" +
	"service_id\x18\b \x01(\tR\tserviceId\x12+\n" +
	"\x03tls\x18\t \x01(\v2\x19.gateon.v1.RouteTLSConfigR\x03tls\x12\x1a\n" +
	"\bdisabled\x18\n" +
	" \x01(\bR\bdisabled\"V\n" +
	"\x0eRouteTLSConfig\x12'\n" +
	"\x0fcertificate_ids\x18\x01 \x03(\tR\x0ecertificateIds\x12\x1b\n" +
	"\toption_id\x18\x02 \x01(\tR\boptionIdB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_route_proto_rawDescOnce sync.Once
	file_gateon_v1_route_proto_rawDescData []byte
)

func file_gateon_v1_route_proto_rawDescGZIP() []byte {
	file_gateon_v1_route_proto_rawDescOnce.Do(func() {
		file_gateon_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_route_proto_rawDesc), len(file_gateon_v1_route_proto_rawDesc)))
	})
	return file_gateon_v1_route_proto_rawDescData
}

var file_gateon_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateon_v1_route_proto_goTypes = []any{
	(*ListRoutesRequest)(nil),   // 0: gateon.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),  // 1: gateon.v1.ListRoutesResponse
	(*UpdateRouteRequest)(nil),  // 2: gateon.v1.UpdateRouteRequest
	(*UpdateRouteResponse)(nil), // 3: gateon.v1.UpdateRouteResponse
	(*DeleteRouteRequest)(nil),  // 4: gateon.v1.DeleteRouteRequest
	(*DeleteRouteResponse)(nil), // 5: gateon.v1.DeleteRouteResponse
	(*Route)(nil),               // 6: gateon.v1.Route
	(*RouteTLSConfig)(nil),      // 7: gateon.v1.RouteTLSConfig
}
var file_gateon_v1_route_proto_depIdxs = []int32{
	6, // 0: gateon.v1.ListRoutesResponse.routes:type_name -> gateon.v1.Route
	6, // 1: gateon.v1.UpdateRouteRequest.route:type_name -> gateon.v1.Route
	7, // 2: gateon.v1.Route.tls:type_name -> gateon.v1.RouteTLSConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateon_v1_route_proto_init() }
func file_gateon_v1_route_proto_init() {
	if File_gateon_v1_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_route_proto_rawDesc), len(file_gateon_v1_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateon_v1_route_proto_goTypes,
		DependencyIndexes: file_gateon_v1_route_proto_depIdxs,
		MessageInfos:      file_gateon_v1_route_proto_msgTypes,
	}.Build()
	File_gateon_v1_route_proto = out.File
	file_gateon_v1_route_proto_goTypes = nil
	file_gateon_v1_route_proto_depIdxs = nil
}
