// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/service.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_gateon_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListServicesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListServicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServicesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_gateon_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListServicesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListServicesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_gateon_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateServiceRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type UpdateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceResponse) Reset() {
	*x = UpdateServiceResponse{}
	mi := &file_gateon_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResponse) ProtoMessage() {}

func (x *UpdateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_gateon_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_gateon_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartCanaryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TargetWeights   []*Target              `protobuf:"bytes,2,rep,name=target_weights,json=targetWeights,proto3" json:"target_weights,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Steps           int32                  `protobuf:"varint,4,opt,name=steps,proto3" json:"steps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartCanaryRequest) Reset() {
	*x = StartCanaryRequest{}
	mi := &file_gateon_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCanaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCanaryRequest) ProtoMessage() {}

func (x *StartCanaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCanaryRequest.ProtoReflect.Descriptor instead.
func (*StartCanaryRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *StartCanaryRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartCanaryRequest) GetTargetWeights() []*Target {
	if x != nil {
		return x.TargetWeights
	}
	return nil
}

func (x *StartCanaryRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *StartCanaryRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

type StartCanaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCanaryResponse) Reset() {
	*x = StartCanaryResponse{}
	mi := &file_gateon_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCanaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCanaryResponse) ProtoMessage() {}

func (x *StartCanaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCanaryResponse.ProtoReflect.Descriptor instead.
func (*StartCanaryResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *StartCanaryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartCanaryResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type Service struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WeightedTargets         []*Target              `protobuf:"bytes,3,rep,name=weighted_targets,json=weightedTargets,proto3" json:"weighted_targets,omitempty"`
	LoadBalancerPolicy      string                 `protobuf:"bytes,4,opt,name=load_balancer_policy,json=loadBalancerPolicy,proto3" json:"load_balancer_policy,omitempty"` // "round_robin", "least_conn", "weighted_round_robin"
	HealthCheckPath         string                 `protobuf:"bytes,5,opt,name=health_check_path,json=healthCheckPath,proto3" json:"health_check_path,omitempty"`
	BackendType             string                 `protobuf:"bytes,6,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"` // "http", "grpc", "graphql", "tcp", "udp"
	L4HealthCheckIntervalMs int32                  `protobuf:"varint,7,opt,name=l4_health_check_interval_ms,json=l4HealthCheckIntervalMs,proto3" json:"l4_health_check_interval_ms,omitempty"`
	L4HealthCheckTimeoutMs  int32                  `protobuf:"varint,8,opt,name=l4_health_check_timeout_ms,json=l4HealthCheckTimeoutMs,proto3" json:"l4_health_check_timeout_ms,omitempty"`
	L4UdpSessionTimeoutS    int32                  `protobuf:"varint,9,opt,name=l4_udp_session_timeout_s,json=l4UdpSessionTimeoutS,proto3" json:"l4_udp_session_timeout_s,omitempty"`
	L4ProxyProtocol         bool                   `protobuf:"varint,10,opt,name=l4_proxy_protocol,json=l4ProxyProtocol,proto3" json:"l4_proxy_protocol,omitempty"` // Send HAProxy PROXY protocol v1 header (TCP only). Enables backend to see original client IP for SPF etc.
	DiscoveryUrl            string                 `protobuf:"bytes,11,opt,name=discovery_url,json=discoveryUrl,proto3" json:"discovery_url,omitempty"`             // e.g. "dns:service.local", "consul:service-name"
	TlsClientConfig         *TlsClientConfig       `protobuf:"bytes,12,opt,name=tls_client_config,json=tlsClientConfig,proto3" json:"tls_client_config,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_gateon_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_gateon_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetWeightedTargets() []*Target {
	if x != nil {
		return x.WeightedTargets
	}
	return nil
}

func (x *Service) GetLoadBalancerPolicy() string {
	if x != nil {
		return x.LoadBalancerPolicy
	}
	return ""
}

func (x *Service) GetHealthCheckPath() string {
	if x != nil {
		return x.HealthCheckPath
	}
	return ""
}

func (x *Service) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *Service) GetL4HealthCheckIntervalMs() int32 {
	if x != nil {
		return x.L4HealthCheckIntervalMs
	}
	return 0
}

func (x *Service) GetL4HealthCheckTimeoutMs() int32 {
	if x != nil {
		return x.L4HealthCheckTimeoutMs
	}
	return 0
}

func (x *Service) GetL4UdpSessionTimeoutS() int32 {
	if x != nil {
		return x.L4UdpSessionTimeoutS
	}
	return 0
}

func (x *Service) GetL4ProxyProtocol() bool {
	if x != nil {
		return x.L4ProxyProtocol
	}
	return false
}

func (x *Service) GetDiscoveryUrl() string {
	if x != nil {
		return x.DiscoveryUrl
	}
	return ""
}

func (x *Service) GetTlsClientConfig() *TlsClientConfig {
	if x != nil {
		return x.TlsClientConfig
	}
	return nil
}

var File_gateon_v1_service_proto protoreflect.FileDescriptor

const file_gateon_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17gateon/v1/service.proto\x12\tgateon.v1\x1a\x16gateon/v1/common.proto\"^\n" +
	"\x13ListServicesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x98\x01\n" +
	"\x14ListServicesResponse\x12.\n" +
	"\bservices\x18\x01 \x03(\v2\x12.gateon.v1.ServiceR\bservices\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"D\n" +
	"\x14UpdateServiceRequest\x12,\n" +
	"\aservice\x18\x01 \x01(\v2\x12.gateon.v1.ServiceR\aservice\"1\n" +
	"\x15UpdateServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14DeleteServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xae\x01\n" +
	"\x12StartCanaryRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x128\n" +
	"\x0etarget_weights\x18\x02 \x03(\v2\x11.gateon.v1.TargetR\rtargetWeights\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\x12\x14\n" +
	"\x05steps\x18\x04 \x01(\x05R\x05steps\"H\n" +
	"\x13StartCanaryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"\xb7\x04\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\x10weighted_targets\x18\x03 \x03(\v2\x11.gateon.v1.TargetR\x0fweightedTargets\x120\n" +
	"\x14load_balancer_policy\x18\x04 \x01(\tR\x12loadBalancerPolicy\x12*\n" +
	"\x11health_check_path\x18\x05 \x01(\tR\x0fhealthCheckPath\x12!\n" +
	"\fbackend_type\x18\x06 \x01(\tR\vbackendType\x12<\n" +
	"\x1bl4_health_check_interval_ms\x18\a \x01(\x05R\x17l4HealthCheckIntervalMs\x12:\n" +
	"\x1al4_health_check_timeout_ms\x18\b \x01(\x05R\x16l4HealthCheckTimeoutMs\x126\n" +
	"\x18l4_udp_session_timeout_s\x18\t \x01(\x05R\x14l4UdpSessionTimeoutS\x12*\n" +
	"\x11l4_proxy_protocol\x18\n" +
	" \x01(\bR\x0fl4ProxyProtocol\x12#\n" +
	"\rdiscovery_url\x18\v \x01(\tR\fdiscoveryUrl\x12F\n" +
	"\x11tls_client_config\x18\f \x01(\v2\x1a.gateon.v1.TlsClientConfigR\x0ftlsClientConfigB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_service_proto_rawDescOnce sync.Once
	file_gateon_v1_service_proto_rawDescData []byte
)

func file_gateon_v1_service_proto_rawDescGZIP() []byte {
	file_gateon_v1_service_proto_rawDescOnce.Do(func() {
		file_gateon_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_service_proto_rawDesc), len(file_gateon_v1_service_proto_rawDesc)))
	})
	return file_gateon_v1_service_proto_rawDescData
}

var file_gateon_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateon_v1_service_proto_goTypes = []any{
	(*ListServicesRequest)(nil),   // 0: gateon.v1.ListServicesRequest
	(*ListServicesResponse)(nil),  // 1: gateon.v1.ListServicesResponse
	(*UpdateServiceRequest)(nil),  // 2: gateon.v1.UpdateServiceRequest
	(*UpdateServiceResponse)(nil), // 3: gateon.v1.UpdateServiceResponse
	(*DeleteServiceRequest)(nil),  // 4: gateon.v1.DeleteServiceRequest
	(*DeleteServiceResponse)(nil), // 5: gateon.v1.DeleteServiceResponse
	(*StartCanaryRequest)(nil),    // 6: gateon.v1.StartCanaryRequest
	(*StartCanaryResponse)(nil),   // 7: gateon.v1.StartCanaryResponse
	(*Service)(nil),               // 8: gateon.v1.Service
	(*Target)(nil),                // 9: gateon.v1.Target
	(*TlsClientConfig)(nil),       // 10: gateon.v1.TlsClientConfig
}
var file_gateon_v1_service_proto_depIdxs = []int32{
	8,  // 0: gateon.v1.ListServicesResponse.services:type_name -> gateon.v1.Service
	8,  // 1: gateon.v1.UpdateServiceRequest.service:type_name -> gateon.v1.Service
	9,  // 2: gateon.v1.StartCanaryRequest.target_weights:type_name -> gateon.v1.Target
	9,  // 3: gateon.v1.Service.weighted_targets:type_name -> gateon.v1.Target
	10, // 4: gateon.v1.Service.tls_client_config:type_name -> gateon.v1.TlsClientConfig
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gateon_v1_service_proto_init() }
func file_gateon_v1_service_proto_init() {
	if File_gateon_v1_service_proto != nil {
		return
	}
	file_gateon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_service_proto_rawDesc), len(file_gateon_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateon_v1_service_proto_goTypes,
		DependencyIndexes: file_gateon_v1_service_proto_depIdxs,
		MessageInfos:      file_gateon_v1_service_proto_msgTypes,
	}.Build()
	File_gateon_v1_service_proto = out.File
	file_gateon_v1_service_proto_goTypes = nil
	file_gateon_v1_service_proto_depIdxs = nil
}
