// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/status.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_gateon_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_status_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	MemoryUsage   int64                  `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	RoutesCount   int32                  `protobuf:"varint,5,opt,name=routes_count,json=routesCount,proto3" json:"routes_count,omitempty"`
	ServicesCount int32                  `protobuf:"varint,6,opt,name=services_count,json=servicesCount,proto3" json:"services_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_gateon_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *GetStatusResponse) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *GetStatusResponse) GetRoutesCount() int32 {
	if x != nil {
		return x.RoutesCount
	}
	return 0
}

func (x *GetStatusResponse) GetServicesCount() int32 {
	if x != nil {
		return x.ServicesCount
	}
	return 0
}

var File_gateon_v1_status_proto protoreflect.FileDescriptor

const file_gateon_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x16gateon/v1/status.proto\x12\tgateon.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xca\x01\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x03R\vmemoryUsage\x12!\n" +
	"\froutes_count\x18\x05 \x01(\x05R\vroutesCount\x12%\n" +
	"\x0eservices_count\x18\x06 \x01(\x05R\rservicesCountB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_status_proto_rawDescOnce sync.Once
	file_gateon_v1_status_proto_rawDescData []byte
)

func file_gateon_v1_status_proto_rawDescGZIP() []byte {
	file_gateon_v1_status_proto_rawDescOnce.Do(func() {
		file_gateon_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_status_proto_rawDesc), len(file_gateon_v1_status_proto_rawDesc)))
	})
	return file_gateon_v1_status_proto_rawDescData
}

var file_gateon_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateon_v1_status_proto_goTypes = []any{
	(*GetStatusRequest)(nil),  // 0: gateon.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: gateon.v1.GetStatusResponse
}
var file_gateon_v1_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateon_v1_status_proto_init() }
func file_gateon_v1_status_proto_init() {
	if File_gateon_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_status_proto_rawDesc), len(file_gateon_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateon_v1_status_proto_goTypes,
		DependencyIndexes: file_gateon_v1_status_proto_depIdxs,
		MessageInfos:      file_gateon_v1_status_proto_msgTypes,
	}.Build()
	File_gateon_v1_status_proto = out.File
	file_gateon_v1_status_proto_goTypes = nil
	file_gateon_v1_status_proto_depIdxs = nil
}
