// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: tls.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTLSOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTLSOptionsRequest) Reset() {
	*x = ListTLSOptionsRequest{}
	mi := &file_tls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTLSOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTLSOptionsRequest) ProtoMessage() {}

func (x *ListTLSOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTLSOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListTLSOptionsRequest) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{0}
}

func (x *ListTLSOptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTLSOptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTLSOptionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListTLSOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TlsOptions    []*TLSOption           `protobuf:"bytes,1,rep,name=tls_options,json=tlsOptions,proto3" json:"tls_options,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTLSOptionsResponse) Reset() {
	*x = ListTLSOptionsResponse{}
	mi := &file_tls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTLSOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTLSOptionsResponse) ProtoMessage() {}

func (x *ListTLSOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTLSOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListTLSOptionsResponse) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{1}
}

func (x *ListTLSOptionsResponse) GetTlsOptions() []*TLSOption {
	if x != nil {
		return x.TlsOptions
	}
	return nil
}

func (x *ListTLSOptionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTLSOptionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTLSOptionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateTLSOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TlsOption     *TLSOption             `protobuf:"bytes,1,opt,name=tls_option,json=tlsOption,proto3" json:"tls_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTLSOptionRequest) Reset() {
	*x = UpdateTLSOptionRequest{}
	mi := &file_tls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTLSOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTLSOptionRequest) ProtoMessage() {}

func (x *UpdateTLSOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTLSOptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTLSOptionRequest) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTLSOptionRequest) GetTlsOption() *TLSOption {
	if x != nil {
		return x.TlsOption
	}
	return nil
}

type UpdateTLSOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTLSOptionResponse) Reset() {
	*x = UpdateTLSOptionResponse{}
	mi := &file_tls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTLSOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTLSOptionResponse) ProtoMessage() {}

func (x *UpdateTLSOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTLSOptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTLSOptionResponse) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTLSOptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTLSOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTLSOptionRequest) Reset() {
	*x = DeleteTLSOptionRequest{}
	mi := &file_tls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTLSOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTLSOptionRequest) ProtoMessage() {}

func (x *DeleteTLSOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTLSOptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTLSOptionRequest) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTLSOptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTLSOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTLSOptionResponse) Reset() {
	*x = DeleteTLSOptionResponse{}
	mi := &file_tls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTLSOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTLSOptionResponse) ProtoMessage() {}

func (x *DeleteTLSOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTLSOptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTLSOptionResponse) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTLSOptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TLSOption struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinTlsVersion            string                 `protobuf:"bytes,3,opt,name=min_tls_version,json=minTlsVersion,proto3" json:"min_tls_version,omitempty"` // "TLS1.0", "TLS1.1", "TLS1.2", "TLS1.3"
	MaxTlsVersion            string                 `protobuf:"bytes,4,opt,name=max_tls_version,json=maxTlsVersion,proto3" json:"max_tls_version,omitempty"`
	CipherSuites             []string               `protobuf:"bytes,5,rep,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	PreferServerCipherSuites bool                   `protobuf:"varint,6,opt,name=prefer_server_cipher_suites,json=preferServerCipherSuites,proto3" json:"prefer_server_cipher_suites,omitempty"`
	ClientAuthType           string                 `protobuf:"bytes,7,opt,name=client_auth_type,json=clientAuthType,proto3" json:"client_auth_type,omitempty"`
	SniStrict                bool                   `protobuf:"varint,8,opt,name=sni_strict,json=sniStrict,proto3" json:"sni_strict,omitempty"`
	AlpnProtocols            []string               `protobuf:"bytes,9,rep,name=alpn_protocols,json=alpnProtocols,proto3" json:"alpn_protocols,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TLSOption) Reset() {
	*x = TLSOption{}
	mi := &file_tls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSOption) ProtoMessage() {}

func (x *TLSOption) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSOption.ProtoReflect.Descriptor instead.
func (*TLSOption) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{6}
}

func (x *TLSOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TLSOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TLSOption) GetMinTlsVersion() string {
	if x != nil {
		return x.MinTlsVersion
	}
	return ""
}

func (x *TLSOption) GetMaxTlsVersion() string {
	if x != nil {
		return x.MaxTlsVersion
	}
	return ""
}

func (x *TLSOption) GetCipherSuites() []string {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *TLSOption) GetPreferServerCipherSuites() bool {
	if x != nil {
		return x.PreferServerCipherSuites
	}
	return false
}

func (x *TLSOption) GetClientAuthType() string {
	if x != nil {
		return x.ClientAuthType
	}
	return ""
}

func (x *TLSOption) GetSniStrict() bool {
	if x != nil {
		return x.SniStrict
	}
	return false
}

func (x *TLSOption) GetAlpnProtocols() []string {
	if x != nil {
		return x.AlpnProtocols
	}
	return nil
}

var File_tls_proto protoreflect.FileDescriptor

const file_tls_proto_rawDesc = "" +
	"\n" +
	"\ttls.proto\x12\tgateon.v1\"`\n" +
	"\x15ListTLSOptionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xa1\x01\n" +
	"\x16ListTLSOptionsResponse\x125\n" +
	"\vtls_options\x18\x01 \x03(\v2\x14.gateon.v1.TLSOptionR\n" +
	"tlsOptions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"M\n" +
	"\x16UpdateTLSOptionRequest\x123\n" +
	"\n" +
	"tls_option\x18\x01 \x01(\v2\x14.gateon.v1.TLSOptionR\ttlsOption\"3\n" +
	"\x17UpdateTLSOptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x16DeleteTLSOptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17DeleteTLSOptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd3\x02\n" +
	"\tTLSOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fmin_tls_version\x18\x03 \x01(\tR\rminTlsVersion\x12&\n" +
	"\x0fmax_tls_version\x18\x04 \x01(\tR\rmaxTlsVersion\x12#\n" +
	"\rcipher_suites\x18\x05 \x03(\tR\fcipherSuites\x12=\n" +
	"\x1bprefer_server_cipher_suites\x18\x06 \x01(\bR\x18preferServerCipherSuites\x12(\n" +
	"\x10client_auth_type\x18\a \x01(\tR\x0eclientAuthType\x12\x1d\n" +
	"\n" +
	"sni_strict\x18\b \x01(\bR\tsniStrict\x12%\n" +
	"\x0ealpn_protocols\x18\t \x03(\tR\ralpnProtocolsB3Z1github.com/gateon/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_tls_proto_rawDescOnce sync.Once
	file_tls_proto_rawDescData []byte
)

func file_tls_proto_rawDescGZIP() []byte {
	file_tls_proto_rawDescOnce.Do(func() {
		file_tls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tls_proto_rawDesc), len(file_tls_proto_rawDesc)))
	})
	return file_tls_proto_rawDescData
}

var file_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tls_proto_goTypes = []any{
	(*ListTLSOptionsRequest)(nil),   // 0: gateon.v1.ListTLSOptionsRequest
	(*ListTLSOptionsResponse)(nil),  // 1: gateon.v1.ListTLSOptionsResponse
	(*UpdateTLSOptionRequest)(nil),  // 2: gateon.v1.UpdateTLSOptionRequest
	(*UpdateTLSOptionResponse)(nil), // 3: gateon.v1.UpdateTLSOptionResponse
	(*DeleteTLSOptionRequest)(nil),  // 4: gateon.v1.DeleteTLSOptionRequest
	(*DeleteTLSOptionResponse)(nil), // 5: gateon.v1.DeleteTLSOptionResponse
	(*TLSOption)(nil),               // 6: gateon.v1.TLSOption
}
var file_tls_proto_depIdxs = []int32{
	6, // 0: gateon.v1.ListTLSOptionsResponse.tls_options:type_name -> gateon.v1.TLSOption
	6, // 1: gateon.v1.UpdateTLSOptionRequest.tls_option:type_name -> gateon.v1.TLSOption
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tls_proto_init() }
func file_tls_proto_init() {
	if File_tls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tls_proto_rawDesc), len(file_tls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tls_proto_goTypes,
		DependencyIndexes: file_tls_proto_depIdxs,
		MessageInfos:      file_tls_proto_msgTypes,
	}.Build()
	File_tls_proto = out.File
	file_tls_proto_goTypes = nil
	file_tls_proto_depIdxs = nil
}
