// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateon/v1/trace.proto

package gateonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_gateon_v1_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_gateon_v1_trace_proto_rawDescGZIP(), []int{0}
}

func (x *Trace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trace) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Trace) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Trace) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Trace) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Trace) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Trace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListTracesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesRequest) Reset() {
	*x = ListTracesRequest{}
	mi := &file_gateon_v1_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesRequest) ProtoMessage() {}

func (x *ListTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesRequest.ProtoReflect.Descriptor instead.
func (*ListTracesRequest) Descriptor() ([]byte, []int) {
	return file_gateon_v1_trace_proto_rawDescGZIP(), []int{1}
}

func (x *ListTracesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTracesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*Trace               `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesResponse) Reset() {
	*x = ListTracesResponse{}
	mi := &file_gateon_v1_trace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesResponse) ProtoMessage() {}

func (x *ListTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateon_v1_trace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesResponse.ProtoReflect.Descriptor instead.
func (*ListTracesResponse) Descriptor() ([]byte, []int) {
	return file_gateon_v1_trace_proto_rawDescGZIP(), []int{2}
}

func (x *ListTracesResponse) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

var File_gateon_v1_trace_proto protoreflect.FileDescriptor

const file_gateon_v1_trace_proto_rawDesc = "" +
	"\n" +
	"\x15gateon/v1/trace.proto\x12\tgateon.v1\"\xcc\x01\n" +
	"\x05Trace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\")\n" +
	"\x11ListTracesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\">\n" +
	"\x12ListTracesResponse\x12(\n" +
	"\x06traces\x18\x01 \x03(\v2\x10.gateon.v1.TraceR\x06tracesB5Z3github.com/gsoultan/gateon/proto/gateon/v1;gateonv1b\x06proto3"

var (
	file_gateon_v1_trace_proto_rawDescOnce sync.Once
	file_gateon_v1_trace_proto_rawDescData []byte
)

func file_gateon_v1_trace_proto_rawDescGZIP() []byte {
	file_gateon_v1_trace_proto_rawDescOnce.Do(func() {
		file_gateon_v1_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateon_v1_trace_proto_rawDesc), len(file_gateon_v1_trace_proto_rawDesc)))
	})
	return file_gateon_v1_trace_proto_rawDescData
}

var file_gateon_v1_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateon_v1_trace_proto_goTypes = []any{
	(*Trace)(nil),              // 0: gateon.v1.Trace
	(*ListTracesRequest)(nil),  // 1: gateon.v1.ListTracesRequest
	(*ListTracesResponse)(nil), // 2: gateon.v1.ListTracesResponse
}
var file_gateon_v1_trace_proto_depIdxs = []int32{
	0, // 0: gateon.v1.ListTracesResponse.traces:type_name -> gateon.v1.Trace
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateon_v1_trace_proto_init() }
func file_gateon_v1_trace_proto_init() {
	if File_gateon_v1_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateon_v1_trace_proto_rawDesc), len(file_gateon_v1_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateon_v1_trace_proto_goTypes,
		DependencyIndexes: file_gateon_v1_trace_proto_depIdxs,
		MessageInfos:      file_gateon_v1_trace_proto_msgTypes,
	}.Build()
	File_gateon_v1_trace_proto = out.File
	file_gateon_v1_trace_proto_goTypes = nil
	file_gateon_v1_trace_proto_depIdxs = nil
}
