// Copyright (c) 2026 Gembit Soultan Shirazi <gembit.soultan@gmail.com>. All rights reserved.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gateon/v1/api.proto

package gateonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gsoultan/gateon/proto/gateon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApiServiceName is the fully-qualified name of the ApiService service.
	ApiServiceName = "gateon.v1.ApiService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApiServiceGetStatusProcedure is the fully-qualified name of the ApiService's GetStatus RPC.
	ApiServiceGetStatusProcedure = "/gateon.v1.ApiService/GetStatus"
	// ApiServiceListTracesProcedure is the fully-qualified name of the ApiService's ListTraces RPC.
	ApiServiceListTracesProcedure = "/gateon.v1.ApiService/ListTraces"
	// ApiServiceGetTraceProcedure is the fully-qualified name of the ApiService's GetTrace RPC.
	ApiServiceGetTraceProcedure = "/gateon.v1.ApiService/GetTrace"
	// ApiServiceListRoutesProcedure is the fully-qualified name of the ApiService's ListRoutes RPC.
	ApiServiceListRoutesProcedure = "/gateon.v1.ApiService/ListRoutes"
	// ApiServiceUpdateRouteProcedure is the fully-qualified name of the ApiService's UpdateRoute RPC.
	ApiServiceUpdateRouteProcedure = "/gateon.v1.ApiService/UpdateRoute"
	// ApiServiceDeleteRouteProcedure is the fully-qualified name of the ApiService's DeleteRoute RPC.
	ApiServiceDeleteRouteProcedure = "/gateon.v1.ApiService/DeleteRoute"
	// ApiServiceListServicesProcedure is the fully-qualified name of the ApiService's ListServices RPC.
	ApiServiceListServicesProcedure = "/gateon.v1.ApiService/ListServices"
	// ApiServiceUpdateServiceProcedure is the fully-qualified name of the ApiService's UpdateService
	// RPC.
	ApiServiceUpdateServiceProcedure = "/gateon.v1.ApiService/UpdateService"
	// ApiServiceDeleteServiceProcedure is the fully-qualified name of the ApiService's DeleteService
	// RPC.
	ApiServiceDeleteServiceProcedure = "/gateon.v1.ApiService/DeleteService"
	// ApiServiceDiscoverGrpcServicesProcedure is the fully-qualified name of the ApiService's
	// DiscoverGrpcServices RPC.
	ApiServiceDiscoverGrpcServicesProcedure = "/gateon.v1.ApiService/DiscoverGrpcServices"
	// ApiServiceDiscoverTechProcedure is the fully-qualified name of the ApiService's DiscoverTech RPC.
	ApiServiceDiscoverTechProcedure = "/gateon.v1.ApiService/DiscoverTech"
	// ApiServiceGetGlobalConfigProcedure is the fully-qualified name of the ApiService's
	// GetGlobalConfig RPC.
	ApiServiceGetGlobalConfigProcedure = "/gateon.v1.ApiService/GetGlobalConfig"
	// ApiServiceUpdateGlobalConfigProcedure is the fully-qualified name of the ApiService's
	// UpdateGlobalConfig RPC.
	ApiServiceUpdateGlobalConfigProcedure = "/gateon.v1.ApiService/UpdateGlobalConfig"
	// ApiServiceListEntryPointsProcedure is the fully-qualified name of the ApiService's
	// ListEntryPoints RPC.
	ApiServiceListEntryPointsProcedure = "/gateon.v1.ApiService/ListEntryPoints"
	// ApiServiceUpdateEntryPointProcedure is the fully-qualified name of the ApiService's
	// UpdateEntryPoint RPC.
	ApiServiceUpdateEntryPointProcedure = "/gateon.v1.ApiService/UpdateEntryPoint"
	// ApiServiceDeleteEntryPointProcedure is the fully-qualified name of the ApiService's
	// DeleteEntryPoint RPC.
	ApiServiceDeleteEntryPointProcedure = "/gateon.v1.ApiService/DeleteEntryPoint"
	// ApiServiceListMiddlewaresProcedure is the fully-qualified name of the ApiService's
	// ListMiddlewares RPC.
	ApiServiceListMiddlewaresProcedure = "/gateon.v1.ApiService/ListMiddlewares"
	// ApiServiceUpdateMiddlewareProcedure is the fully-qualified name of the ApiService's
	// UpdateMiddleware RPC.
	ApiServiceUpdateMiddlewareProcedure = "/gateon.v1.ApiService/UpdateMiddleware"
	// ApiServiceDeleteMiddlewareProcedure is the fully-qualified name of the ApiService's
	// DeleteMiddleware RPC.
	ApiServiceDeleteMiddlewareProcedure = "/gateon.v1.ApiService/DeleteMiddleware"
	// ApiServiceGetCloudflareIPsProcedure is the fully-qualified name of the ApiService's
	// GetCloudflareIPs RPC.
	ApiServiceGetCloudflareIPsProcedure = "/gateon.v1.ApiService/GetCloudflareIPs"
	// ApiServiceListTLSOptionsProcedure is the fully-qualified name of the ApiService's ListTLSOptions
	// RPC.
	ApiServiceListTLSOptionsProcedure = "/gateon.v1.ApiService/ListTLSOptions"
	// ApiServiceUpdateTLSOptionProcedure is the fully-qualified name of the ApiService's
	// UpdateTLSOption RPC.
	ApiServiceUpdateTLSOptionProcedure = "/gateon.v1.ApiService/UpdateTLSOption"
	// ApiServiceDeleteTLSOptionProcedure is the fully-qualified name of the ApiService's
	// DeleteTLSOption RPC.
	ApiServiceDeleteTLSOptionProcedure = "/gateon.v1.ApiService/DeleteTLSOption"
	// ApiServiceLoginProcedure is the fully-qualified name of the ApiService's Login RPC.
	ApiServiceLoginProcedure = "/gateon.v1.ApiService/Login"
	// ApiServiceIsSetupRequiredProcedure is the fully-qualified name of the ApiService's
	// IsSetupRequired RPC.
	ApiServiceIsSetupRequiredProcedure = "/gateon.v1.ApiService/IsSetupRequired"
	// ApiServiceSetupProcedure is the fully-qualified name of the ApiService's Setup RPC.
	ApiServiceSetupProcedure = "/gateon.v1.ApiService/Setup"
	// ApiServiceChangePasswordProcedure is the fully-qualified name of the ApiService's ChangePassword
	// RPC.
	ApiServiceChangePasswordProcedure = "/gateon.v1.ApiService/ChangePassword"
	// ApiServiceListUsersProcedure is the fully-qualified name of the ApiService's ListUsers RPC.
	ApiServiceListUsersProcedure = "/gateon.v1.ApiService/ListUsers"
	// ApiServiceUpdateUserProcedure is the fully-qualified name of the ApiService's UpdateUser RPC.
	ApiServiceUpdateUserProcedure = "/gateon.v1.ApiService/UpdateUser"
	// ApiServiceDeleteUserProcedure is the fully-qualified name of the ApiService's DeleteUser RPC.
	ApiServiceDeleteUserProcedure = "/gateon.v1.ApiService/DeleteUser"
	// ApiServiceGetDiagnosticsProcedure is the fully-qualified name of the ApiService's GetDiagnostics
	// RPC.
	ApiServiceGetDiagnosticsProcedure = "/gateon.v1.ApiService/GetDiagnostics"
	// ApiServiceListSecurityThreatsProcedure is the fully-qualified name of the ApiService's
	// ListSecurityThreats RPC.
	ApiServiceListSecurityThreatsProcedure = "/gateon.v1.ApiService/ListSecurityThreats"
	// ApiServiceGetSecurityThreatProcedure is the fully-qualified name of the ApiService's
	// GetSecurityThreat RPC.
	ApiServiceGetSecurityThreatProcedure = "/gateon.v1.ApiService/GetSecurityThreat"
	// ApiServiceMitigateThreatProcedure is the fully-qualified name of the ApiService's MitigateThreat
	// RPC.
	ApiServiceMitigateThreatProcedure = "/gateon.v1.ApiService/MitigateThreat"
	// ApiServiceRemoveMitigatedThreatProcedure is the fully-qualified name of the ApiService's
	// RemoveMitigatedThreat RPC.
	ApiServiceRemoveMitigatedThreatProcedure = "/gateon.v1.ApiService/RemoveMitigatedThreat"
	// ApiServiceListReputationsProcedure is the fully-qualified name of the ApiService's
	// ListReputations RPC.
	ApiServiceListReputationsProcedure = "/gateon.v1.ApiService/ListReputations"
	// ApiServiceListAuditLogsProcedure is the fully-qualified name of the ApiService's ListAuditLogs
	// RPC.
	ApiServiceListAuditLogsProcedure = "/gateon.v1.ApiService/ListAuditLogs"
	// ApiServiceListAuditArchivesProcedure is the fully-qualified name of the ApiService's
	// ListAuditArchives RPC.
	ApiServiceListAuditArchivesProcedure = "/gateon.v1.ApiService/ListAuditArchives"
	// ApiServiceGetAuditArchiveProcedure is the fully-qualified name of the ApiService's
	// GetAuditArchive RPC.
	ApiServiceGetAuditArchiveProcedure = "/gateon.v1.ApiService/GetAuditArchive"
	// ApiServiceApplyRecommendationProcedure is the fully-qualified name of the ApiService's
	// ApplyRecommendation RPC.
	ApiServiceApplyRecommendationProcedure = "/gateon.v1.ApiService/ApplyRecommendation"
	// ApiServiceTriggerWafUpdateProcedure is the fully-qualified name of the ApiService's
	// TriggerWafUpdate RPC.
	ApiServiceTriggerWafUpdateProcedure = "/gateon.v1.ApiService/TriggerWafUpdate"
	// ApiServiceTraceRouteProcedure is the fully-qualified name of the ApiService's TraceRoute RPC.
	ApiServiceTraceRouteProcedure = "/gateon.v1.ApiService/TraceRoute"
	// ApiServiceValidateCORSProcedure is the fully-qualified name of the ApiService's ValidateCORS RPC.
	ApiServiceValidateCORSProcedure = "/gateon.v1.ApiService/ValidateCORS"
	// ApiServiceInstallClamavProcedure is the fully-qualified name of the ApiService's InstallClamav
	// RPC.
	ApiServiceInstallClamavProcedure = "/gateon.v1.ApiService/InstallClamav"
	// ApiServiceUninstallClamavProcedure is the fully-qualified name of the ApiService's
	// UninstallClamav RPC.
	ApiServiceUninstallClamavProcedure = "/gateon.v1.ApiService/UninstallClamav"
	// ApiServiceRunDeepScanProcedure is the fully-qualified name of the ApiService's RunDeepScan RPC.
	ApiServiceRunDeepScanProcedure = "/gateon.v1.ApiService/RunDeepScan"
	// ApiServiceListWafRulesProcedure is the fully-qualified name of the ApiService's ListWafRules RPC.
	ApiServiceListWafRulesProcedure = "/gateon.v1.ApiService/ListWafRules"
	// ApiServiceCreateWafRuleProcedure is the fully-qualified name of the ApiService's CreateWafRule
	// RPC.
	ApiServiceCreateWafRuleProcedure = "/gateon.v1.ApiService/CreateWafRule"
	// ApiServiceUpdateWafRuleProcedure is the fully-qualified name of the ApiService's UpdateWafRule
	// RPC.
	ApiServiceUpdateWafRuleProcedure = "/gateon.v1.ApiService/UpdateWafRule"
	// ApiServiceDeleteWafRuleProcedure is the fully-qualified name of the ApiService's DeleteWafRule
	// RPC.
	ApiServiceDeleteWafRuleProcedure = "/gateon.v1.ApiService/DeleteWafRule"
)

// ApiServiceClient is a client for the gateon.v1.ApiService service.
type ApiServiceClient interface {
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	ListTraces(context.Context, *connect.Request[v1.ListTracesRequest]) (*connect.Response[v1.ListTracesResponse], error)
	GetTrace(context.Context, *connect.Request[v1.GetTraceRequest]) (*connect.Response[v1.GetTraceResponse], error)
	ListRoutes(context.Context, *connect.Request[v1.ListRoutesRequest]) (*connect.Response[v1.ListRoutesResponse], error)
	UpdateRoute(context.Context, *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error)
	DeleteRoute(context.Context, *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[v1.DeleteRouteResponse], error)
	ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error)
	UpdateService(context.Context, *connect.Request[v1.UpdateServiceRequest]) (*connect.Response[v1.UpdateServiceResponse], error)
	DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error)
	DiscoverGrpcServices(context.Context, *connect.Request[v1.DiscoverGrpcServicesRequest]) (*connect.Response[v1.DiscoverGrpcServicesResponse], error)
	DiscoverTech(context.Context, *connect.Request[v1.DiscoverTechRequest]) (*connect.Response[v1.DiscoverTechResponse], error)
	GetGlobalConfig(context.Context, *connect.Request[v1.GetGlobalConfigRequest]) (*connect.Response[v1.GetGlobalConfigResponse], error)
	UpdateGlobalConfig(context.Context, *connect.Request[v1.UpdateGlobalConfigRequest]) (*connect.Response[v1.UpdateGlobalConfigResponse], error)
	ListEntryPoints(context.Context, *connect.Request[v1.ListEntryPointsRequest]) (*connect.Response[v1.ListEntryPointsResponse], error)
	UpdateEntryPoint(context.Context, *connect.Request[v1.UpdateEntryPointRequest]) (*connect.Response[v1.UpdateEntryPointResponse], error)
	DeleteEntryPoint(context.Context, *connect.Request[v1.DeleteEntryPointRequest]) (*connect.Response[v1.DeleteEntryPointResponse], error)
	ListMiddlewares(context.Context, *connect.Request[v1.ListMiddlewaresRequest]) (*connect.Response[v1.ListMiddlewaresResponse], error)
	UpdateMiddleware(context.Context, *connect.Request[v1.UpdateMiddlewareRequest]) (*connect.Response[v1.UpdateMiddlewareResponse], error)
	DeleteMiddleware(context.Context, *connect.Request[v1.DeleteMiddlewareRequest]) (*connect.Response[v1.DeleteMiddlewareResponse], error)
	GetCloudflareIPs(context.Context, *connect.Request[v1.GetCloudflareIPsRequest]) (*connect.Response[v1.GetCloudflareIPsResponse], error)
	ListTLSOptions(context.Context, *connect.Request[v1.ListTLSOptionsRequest]) (*connect.Response[v1.ListTLSOptionsResponse], error)
	UpdateTLSOption(context.Context, *connect.Request[v1.UpdateTLSOptionRequest]) (*connect.Response[v1.UpdateTLSOptionResponse], error)
	DeleteTLSOption(context.Context, *connect.Request[v1.DeleteTLSOptionRequest]) (*connect.Response[v1.DeleteTLSOptionResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	IsSetupRequired(context.Context, *connect.Request[v1.IsSetupRequiredRequest]) (*connect.Response[v1.IsSetupRequiredResponse], error)
	Setup(context.Context, *connect.Request[v1.SetupRequest]) (*connect.Response[v1.SetupResponse], error)
	ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error)
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	GetDiagnostics(context.Context, *connect.Request[v1.GetDiagnosticsRequest]) (*connect.Response[v1.GetDiagnosticsResponse], error)
	ListSecurityThreats(context.Context, *connect.Request[v1.ListSecurityThreatsRequest]) (*connect.Response[v1.ListSecurityThreatsResponse], error)
	GetSecurityThreat(context.Context, *connect.Request[v1.GetSecurityThreatRequest]) (*connect.Response[v1.GetSecurityThreatResponse], error)
	MitigateThreat(context.Context, *connect.Request[v1.MitigateThreatRequest]) (*connect.Response[v1.MitigateThreatResponse], error)
	RemoveMitigatedThreat(context.Context, *connect.Request[v1.RemoveMitigatedThreatRequest]) (*connect.Response[v1.RemoveMitigatedThreatResponse], error)
	ListReputations(context.Context, *connect.Request[v1.ListReputationsRequest]) (*connect.Response[v1.ListReputationsResponse], error)
	ListAuditLogs(context.Context, *connect.Request[v1.ListAuditLogsRequest]) (*connect.Response[v1.ListAuditLogsResponse], error)
	ListAuditArchives(context.Context, *connect.Request[v1.ListAuditArchivesRequest]) (*connect.Response[v1.ListAuditArchivesResponse], error)
	GetAuditArchive(context.Context, *connect.Request[v1.GetAuditArchiveRequest]) (*connect.Response[v1.GetAuditArchiveResponse], error)
	ApplyRecommendation(context.Context, *connect.Request[v1.ApplyRecommendationRequest]) (*connect.Response[v1.ApplyRecommendationResponse], error)
	TriggerWafUpdate(context.Context, *connect.Request[v1.TriggerWafUpdateRequest]) (*connect.Response[v1.TriggerWafUpdateResponse], error)
	TraceRoute(context.Context, *connect.Request[v1.TraceRouteRequest]) (*connect.Response[v1.TraceRouteResponse], error)
	ValidateCORS(context.Context, *connect.Request[v1.ValidateCORSRequest]) (*connect.Response[v1.ValidateCORSResponse], error)
	InstallClamav(context.Context, *connect.Request[v1.InstallClamavRequest]) (*connect.Response[v1.InstallClamavResponse], error)
	UninstallClamav(context.Context, *connect.Request[v1.UninstallClamavRequest]) (*connect.Response[v1.UninstallClamavResponse], error)
	RunDeepScan(context.Context, *connect.Request[v1.RunDeepScanRequest]) (*connect.Response[v1.RunDeepScanResponse], error)
	ListWafRules(context.Context, *connect.Request[v1.ListWafRulesRequest]) (*connect.Response[v1.ListWafRulesResponse], error)
	CreateWafRule(context.Context, *connect.Request[v1.CreateWafRuleRequest]) (*connect.Response[v1.CreateWafRuleResponse], error)
	UpdateWafRule(context.Context, *connect.Request[v1.UpdateWafRuleRequest]) (*connect.Response[v1.UpdateWafRuleResponse], error)
	DeleteWafRule(context.Context, *connect.Request[v1.DeleteWafRuleRequest]) (*connect.Response[v1.DeleteWafRuleResponse], error)
}

// NewApiServiceClient constructs a client for the gateon.v1.ApiService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApiServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApiServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	apiServiceMethods := v1.File_gateon_v1_api_proto.Services().ByName("ApiService").Methods()
	return &apiServiceClient{
		getStatus: connect.NewClient[v1.GetStatusRequest, v1.GetStatusResponse](
			httpClient,
			baseURL+ApiServiceGetStatusProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		listTraces: connect.NewClient[v1.ListTracesRequest, v1.ListTracesResponse](
			httpClient,
			baseURL+ApiServiceListTracesProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListTraces")),
			connect.WithClientOptions(opts...),
		),
		getTrace: connect.NewClient[v1.GetTraceRequest, v1.GetTraceResponse](
			httpClient,
			baseURL+ApiServiceGetTraceProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetTrace")),
			connect.WithClientOptions(opts...),
		),
		listRoutes: connect.NewClient[v1.ListRoutesRequest, v1.ListRoutesResponse](
			httpClient,
			baseURL+ApiServiceListRoutesProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListRoutes")),
			connect.WithClientOptions(opts...),
		),
		updateRoute: connect.NewClient[v1.UpdateRouteRequest, v1.UpdateRouteResponse](
			httpClient,
			baseURL+ApiServiceUpdateRouteProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateRoute")),
			connect.WithClientOptions(opts...),
		),
		deleteRoute: connect.NewClient[v1.DeleteRouteRequest, v1.DeleteRouteResponse](
			httpClient,
			baseURL+ApiServiceDeleteRouteProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteRoute")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[v1.ListServicesRequest, v1.ListServicesResponse](
			httpClient,
			baseURL+ApiServiceListServicesProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		updateService: connect.NewClient[v1.UpdateServiceRequest, v1.UpdateServiceResponse](
			httpClient,
			baseURL+ApiServiceUpdateServiceProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateService")),
			connect.WithClientOptions(opts...),
		),
		deleteService: connect.NewClient[v1.DeleteServiceRequest, v1.DeleteServiceResponse](
			httpClient,
			baseURL+ApiServiceDeleteServiceProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteService")),
			connect.WithClientOptions(opts...),
		),
		discoverGrpcServices: connect.NewClient[v1.DiscoverGrpcServicesRequest, v1.DiscoverGrpcServicesResponse](
			httpClient,
			baseURL+ApiServiceDiscoverGrpcServicesProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DiscoverGrpcServices")),
			connect.WithClientOptions(opts...),
		),
		discoverTech: connect.NewClient[v1.DiscoverTechRequest, v1.DiscoverTechResponse](
			httpClient,
			baseURL+ApiServiceDiscoverTechProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DiscoverTech")),
			connect.WithClientOptions(opts...),
		),
		getGlobalConfig: connect.NewClient[v1.GetGlobalConfigRequest, v1.GetGlobalConfigResponse](
			httpClient,
			baseURL+ApiServiceGetGlobalConfigProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetGlobalConfig")),
			connect.WithClientOptions(opts...),
		),
		updateGlobalConfig: connect.NewClient[v1.UpdateGlobalConfigRequest, v1.UpdateGlobalConfigResponse](
			httpClient,
			baseURL+ApiServiceUpdateGlobalConfigProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateGlobalConfig")),
			connect.WithClientOptions(opts...),
		),
		listEntryPoints: connect.NewClient[v1.ListEntryPointsRequest, v1.ListEntryPointsResponse](
			httpClient,
			baseURL+ApiServiceListEntryPointsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListEntryPoints")),
			connect.WithClientOptions(opts...),
		),
		updateEntryPoint: connect.NewClient[v1.UpdateEntryPointRequest, v1.UpdateEntryPointResponse](
			httpClient,
			baseURL+ApiServiceUpdateEntryPointProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateEntryPoint")),
			connect.WithClientOptions(opts...),
		),
		deleteEntryPoint: connect.NewClient[v1.DeleteEntryPointRequest, v1.DeleteEntryPointResponse](
			httpClient,
			baseURL+ApiServiceDeleteEntryPointProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteEntryPoint")),
			connect.WithClientOptions(opts...),
		),
		listMiddlewares: connect.NewClient[v1.ListMiddlewaresRequest, v1.ListMiddlewaresResponse](
			httpClient,
			baseURL+ApiServiceListMiddlewaresProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListMiddlewares")),
			connect.WithClientOptions(opts...),
		),
		updateMiddleware: connect.NewClient[v1.UpdateMiddlewareRequest, v1.UpdateMiddlewareResponse](
			httpClient,
			baseURL+ApiServiceUpdateMiddlewareProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateMiddleware")),
			connect.WithClientOptions(opts...),
		),
		deleteMiddleware: connect.NewClient[v1.DeleteMiddlewareRequest, v1.DeleteMiddlewareResponse](
			httpClient,
			baseURL+ApiServiceDeleteMiddlewareProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteMiddleware")),
			connect.WithClientOptions(opts...),
		),
		getCloudflareIPs: connect.NewClient[v1.GetCloudflareIPsRequest, v1.GetCloudflareIPsResponse](
			httpClient,
			baseURL+ApiServiceGetCloudflareIPsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetCloudflareIPs")),
			connect.WithClientOptions(opts...),
		),
		listTLSOptions: connect.NewClient[v1.ListTLSOptionsRequest, v1.ListTLSOptionsResponse](
			httpClient,
			baseURL+ApiServiceListTLSOptionsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListTLSOptions")),
			connect.WithClientOptions(opts...),
		),
		updateTLSOption: connect.NewClient[v1.UpdateTLSOptionRequest, v1.UpdateTLSOptionResponse](
			httpClient,
			baseURL+ApiServiceUpdateTLSOptionProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateTLSOption")),
			connect.WithClientOptions(opts...),
		),
		deleteTLSOption: connect.NewClient[v1.DeleteTLSOptionRequest, v1.DeleteTLSOptionResponse](
			httpClient,
			baseURL+ApiServiceDeleteTLSOptionProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteTLSOption")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+ApiServiceLoginProcedure,
			connect.WithSchema(apiServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		isSetupRequired: connect.NewClient[v1.IsSetupRequiredRequest, v1.IsSetupRequiredResponse](
			httpClient,
			baseURL+ApiServiceIsSetupRequiredProcedure,
			connect.WithSchema(apiServiceMethods.ByName("IsSetupRequired")),
			connect.WithClientOptions(opts...),
		),
		setup: connect.NewClient[v1.SetupRequest, v1.SetupResponse](
			httpClient,
			baseURL+ApiServiceSetupProcedure,
			connect.WithSchema(apiServiceMethods.ByName("Setup")),
			connect.WithClientOptions(opts...),
		),
		changePassword: connect.NewClient[v1.ChangePasswordRequest, v1.ChangePasswordResponse](
			httpClient,
			baseURL+ApiServiceChangePasswordProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ChangePassword")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+ApiServiceListUsersProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+ApiServiceUpdateUserProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+ApiServiceDeleteUserProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		getDiagnostics: connect.NewClient[v1.GetDiagnosticsRequest, v1.GetDiagnosticsResponse](
			httpClient,
			baseURL+ApiServiceGetDiagnosticsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetDiagnostics")),
			connect.WithClientOptions(opts...),
		),
		listSecurityThreats: connect.NewClient[v1.ListSecurityThreatsRequest, v1.ListSecurityThreatsResponse](
			httpClient,
			baseURL+ApiServiceListSecurityThreatsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListSecurityThreats")),
			connect.WithClientOptions(opts...),
		),
		getSecurityThreat: connect.NewClient[v1.GetSecurityThreatRequest, v1.GetSecurityThreatResponse](
			httpClient,
			baseURL+ApiServiceGetSecurityThreatProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetSecurityThreat")),
			connect.WithClientOptions(opts...),
		),
		mitigateThreat: connect.NewClient[v1.MitigateThreatRequest, v1.MitigateThreatResponse](
			httpClient,
			baseURL+ApiServiceMitigateThreatProcedure,
			connect.WithSchema(apiServiceMethods.ByName("MitigateThreat")),
			connect.WithClientOptions(opts...),
		),
		removeMitigatedThreat: connect.NewClient[v1.RemoveMitigatedThreatRequest, v1.RemoveMitigatedThreatResponse](
			httpClient,
			baseURL+ApiServiceRemoveMitigatedThreatProcedure,
			connect.WithSchema(apiServiceMethods.ByName("RemoveMitigatedThreat")),
			connect.WithClientOptions(opts...),
		),
		listReputations: connect.NewClient[v1.ListReputationsRequest, v1.ListReputationsResponse](
			httpClient,
			baseURL+ApiServiceListReputationsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListReputations")),
			connect.WithClientOptions(opts...),
		),
		listAuditLogs: connect.NewClient[v1.ListAuditLogsRequest, v1.ListAuditLogsResponse](
			httpClient,
			baseURL+ApiServiceListAuditLogsProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListAuditLogs")),
			connect.WithClientOptions(opts...),
		),
		listAuditArchives: connect.NewClient[v1.ListAuditArchivesRequest, v1.ListAuditArchivesResponse](
			httpClient,
			baseURL+ApiServiceListAuditArchivesProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListAuditArchives")),
			connect.WithClientOptions(opts...),
		),
		getAuditArchive: connect.NewClient[v1.GetAuditArchiveRequest, v1.GetAuditArchiveResponse](
			httpClient,
			baseURL+ApiServiceGetAuditArchiveProcedure,
			connect.WithSchema(apiServiceMethods.ByName("GetAuditArchive")),
			connect.WithClientOptions(opts...),
		),
		applyRecommendation: connect.NewClient[v1.ApplyRecommendationRequest, v1.ApplyRecommendationResponse](
			httpClient,
			baseURL+ApiServiceApplyRecommendationProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ApplyRecommendation")),
			connect.WithClientOptions(opts...),
		),
		triggerWafUpdate: connect.NewClient[v1.TriggerWafUpdateRequest, v1.TriggerWafUpdateResponse](
			httpClient,
			baseURL+ApiServiceTriggerWafUpdateProcedure,
			connect.WithSchema(apiServiceMethods.ByName("TriggerWafUpdate")),
			connect.WithClientOptions(opts...),
		),
		traceRoute: connect.NewClient[v1.TraceRouteRequest, v1.TraceRouteResponse](
			httpClient,
			baseURL+ApiServiceTraceRouteProcedure,
			connect.WithSchema(apiServiceMethods.ByName("TraceRoute")),
			connect.WithClientOptions(opts...),
		),
		validateCORS: connect.NewClient[v1.ValidateCORSRequest, v1.ValidateCORSResponse](
			httpClient,
			baseURL+ApiServiceValidateCORSProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ValidateCORS")),
			connect.WithClientOptions(opts...),
		),
		installClamav: connect.NewClient[v1.InstallClamavRequest, v1.InstallClamavResponse](
			httpClient,
			baseURL+ApiServiceInstallClamavProcedure,
			connect.WithSchema(apiServiceMethods.ByName("InstallClamav")),
			connect.WithClientOptions(opts...),
		),
		uninstallClamav: connect.NewClient[v1.UninstallClamavRequest, v1.UninstallClamavResponse](
			httpClient,
			baseURL+ApiServiceUninstallClamavProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UninstallClamav")),
			connect.WithClientOptions(opts...),
		),
		runDeepScan: connect.NewClient[v1.RunDeepScanRequest, v1.RunDeepScanResponse](
			httpClient,
			baseURL+ApiServiceRunDeepScanProcedure,
			connect.WithSchema(apiServiceMethods.ByName("RunDeepScan")),
			connect.WithClientOptions(opts...),
		),
		listWafRules: connect.NewClient[v1.ListWafRulesRequest, v1.ListWafRulesResponse](
			httpClient,
			baseURL+ApiServiceListWafRulesProcedure,
			connect.WithSchema(apiServiceMethods.ByName("ListWafRules")),
			connect.WithClientOptions(opts...),
		),
		createWafRule: connect.NewClient[v1.CreateWafRuleRequest, v1.CreateWafRuleResponse](
			httpClient,
			baseURL+ApiServiceCreateWafRuleProcedure,
			connect.WithSchema(apiServiceMethods.ByName("CreateWafRule")),
			connect.WithClientOptions(opts...),
		),
		updateWafRule: connect.NewClient[v1.UpdateWafRuleRequest, v1.UpdateWafRuleResponse](
			httpClient,
			baseURL+ApiServiceUpdateWafRuleProcedure,
			connect.WithSchema(apiServiceMethods.ByName("UpdateWafRule")),
			connect.WithClientOptions(opts...),
		),
		deleteWafRule: connect.NewClient[v1.DeleteWafRuleRequest, v1.DeleteWafRuleResponse](
			httpClient,
			baseURL+ApiServiceDeleteWafRuleProcedure,
			connect.WithSchema(apiServiceMethods.ByName("DeleteWafRule")),
			connect.WithClientOptions(opts...),
		),
	}
}

// apiServiceClient implements ApiServiceClient.
type apiServiceClient struct {
	getStatus             *connect.Client[v1.GetStatusRequest, v1.GetStatusResponse]
	listTraces            *connect.Client[v1.ListTracesRequest, v1.ListTracesResponse]
	getTrace              *connect.Client[v1.GetTraceRequest, v1.GetTraceResponse]
	listRoutes            *connect.Client[v1.ListRoutesRequest, v1.ListRoutesResponse]
	updateRoute           *connect.Client[v1.UpdateRouteRequest, v1.UpdateRouteResponse]
	deleteRoute           *connect.Client[v1.DeleteRouteRequest, v1.DeleteRouteResponse]
	listServices          *connect.Client[v1.ListServicesRequest, v1.ListServicesResponse]
	updateService         *connect.Client[v1.UpdateServiceRequest, v1.UpdateServiceResponse]
	deleteService         *connect.Client[v1.DeleteServiceRequest, v1.DeleteServiceResponse]
	discoverGrpcServices  *connect.Client[v1.DiscoverGrpcServicesRequest, v1.DiscoverGrpcServicesResponse]
	discoverTech          *connect.Client[v1.DiscoverTechRequest, v1.DiscoverTechResponse]
	getGlobalConfig       *connect.Client[v1.GetGlobalConfigRequest, v1.GetGlobalConfigResponse]
	updateGlobalConfig    *connect.Client[v1.UpdateGlobalConfigRequest, v1.UpdateGlobalConfigResponse]
	listEntryPoints       *connect.Client[v1.ListEntryPointsRequest, v1.ListEntryPointsResponse]
	updateEntryPoint      *connect.Client[v1.UpdateEntryPointRequest, v1.UpdateEntryPointResponse]
	deleteEntryPoint      *connect.Client[v1.DeleteEntryPointRequest, v1.DeleteEntryPointResponse]
	listMiddlewares       *connect.Client[v1.ListMiddlewaresRequest, v1.ListMiddlewaresResponse]
	updateMiddleware      *connect.Client[v1.UpdateMiddlewareRequest, v1.UpdateMiddlewareResponse]
	deleteMiddleware      *connect.Client[v1.DeleteMiddlewareRequest, v1.DeleteMiddlewareResponse]
	getCloudflareIPs      *connect.Client[v1.GetCloudflareIPsRequest, v1.GetCloudflareIPsResponse]
	listTLSOptions        *connect.Client[v1.ListTLSOptionsRequest, v1.ListTLSOptionsResponse]
	updateTLSOption       *connect.Client[v1.UpdateTLSOptionRequest, v1.UpdateTLSOptionResponse]
	deleteTLSOption       *connect.Client[v1.DeleteTLSOptionRequest, v1.DeleteTLSOptionResponse]
	login                 *connect.Client[v1.LoginRequest, v1.LoginResponse]
	isSetupRequired       *connect.Client[v1.IsSetupRequiredRequest, v1.IsSetupRequiredResponse]
	setup                 *connect.Client[v1.SetupRequest, v1.SetupResponse]
	changePassword        *connect.Client[v1.ChangePasswordRequest, v1.ChangePasswordResponse]
	listUsers             *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	updateUser            *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	deleteUser            *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
	getDiagnostics        *connect.Client[v1.GetDiagnosticsRequest, v1.GetDiagnosticsResponse]
	listSecurityThreats   *connect.Client[v1.ListSecurityThreatsRequest, v1.ListSecurityThreatsResponse]
	getSecurityThreat     *connect.Client[v1.GetSecurityThreatRequest, v1.GetSecurityThreatResponse]
	mitigateThreat        *connect.Client[v1.MitigateThreatRequest, v1.MitigateThreatResponse]
	removeMitigatedThreat *connect.Client[v1.RemoveMitigatedThreatRequest, v1.RemoveMitigatedThreatResponse]
	listReputations       *connect.Client[v1.ListReputationsRequest, v1.ListReputationsResponse]
	listAuditLogs         *connect.Client[v1.ListAuditLogsRequest, v1.ListAuditLogsResponse]
	listAuditArchives     *connect.Client[v1.ListAuditArchivesRequest, v1.ListAuditArchivesResponse]
	getAuditArchive       *connect.Client[v1.GetAuditArchiveRequest, v1.GetAuditArchiveResponse]
	applyRecommendation   *connect.Client[v1.ApplyRecommendationRequest, v1.ApplyRecommendationResponse]
	triggerWafUpdate      *connect.Client[v1.TriggerWafUpdateRequest, v1.TriggerWafUpdateResponse]
	traceRoute            *connect.Client[v1.TraceRouteRequest, v1.TraceRouteResponse]
	validateCORS          *connect.Client[v1.ValidateCORSRequest, v1.ValidateCORSResponse]
	installClamav         *connect.Client[v1.InstallClamavRequest, v1.InstallClamavResponse]
	uninstallClamav       *connect.Client[v1.UninstallClamavRequest, v1.UninstallClamavResponse]
	runDeepScan           *connect.Client[v1.RunDeepScanRequest, v1.RunDeepScanResponse]
	listWafRules          *connect.Client[v1.ListWafRulesRequest, v1.ListWafRulesResponse]
	createWafRule         *connect.Client[v1.CreateWafRuleRequest, v1.CreateWafRuleResponse]
	updateWafRule         *connect.Client[v1.UpdateWafRuleRequest, v1.UpdateWafRuleResponse]
	deleteWafRule         *connect.Client[v1.DeleteWafRuleRequest, v1.DeleteWafRuleResponse]
}

// GetStatus calls gateon.v1.ApiService.GetStatus.
func (c *apiServiceClient) GetStatus(ctx context.Context, req *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// ListTraces calls gateon.v1.ApiService.ListTraces.
func (c *apiServiceClient) ListTraces(ctx context.Context, req *connect.Request[v1.ListTracesRequest]) (*connect.Response[v1.ListTracesResponse], error) {
	return c.listTraces.CallUnary(ctx, req)
}

// GetTrace calls gateon.v1.ApiService.GetTrace.
func (c *apiServiceClient) GetTrace(ctx context.Context, req *connect.Request[v1.GetTraceRequest]) (*connect.Response[v1.GetTraceResponse], error) {
	return c.getTrace.CallUnary(ctx, req)
}

// ListRoutes calls gateon.v1.ApiService.ListRoutes.
func (c *apiServiceClient) ListRoutes(ctx context.Context, req *connect.Request[v1.ListRoutesRequest]) (*connect.Response[v1.ListRoutesResponse], error) {
	return c.listRoutes.CallUnary(ctx, req)
}

// UpdateRoute calls gateon.v1.ApiService.UpdateRoute.
func (c *apiServiceClient) UpdateRoute(ctx context.Context, req *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error) {
	return c.updateRoute.CallUnary(ctx, req)
}

// DeleteRoute calls gateon.v1.ApiService.DeleteRoute.
func (c *apiServiceClient) DeleteRoute(ctx context.Context, req *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[v1.DeleteRouteResponse], error) {
	return c.deleteRoute.CallUnary(ctx, req)
}

// ListServices calls gateon.v1.ApiService.ListServices.
func (c *apiServiceClient) ListServices(ctx context.Context, req *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

// UpdateService calls gateon.v1.ApiService.UpdateService.
func (c *apiServiceClient) UpdateService(ctx context.Context, req *connect.Request[v1.UpdateServiceRequest]) (*connect.Response[v1.UpdateServiceResponse], error) {
	return c.updateService.CallUnary(ctx, req)
}

// DeleteService calls gateon.v1.ApiService.DeleteService.
func (c *apiServiceClient) DeleteService(ctx context.Context, req *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return c.deleteService.CallUnary(ctx, req)
}

// DiscoverGrpcServices calls gateon.v1.ApiService.DiscoverGrpcServices.
func (c *apiServiceClient) DiscoverGrpcServices(ctx context.Context, req *connect.Request[v1.DiscoverGrpcServicesRequest]) (*connect.Response[v1.DiscoverGrpcServicesResponse], error) {
	return c.discoverGrpcServices.CallUnary(ctx, req)
}

// DiscoverTech calls gateon.v1.ApiService.DiscoverTech.
func (c *apiServiceClient) DiscoverTech(ctx context.Context, req *connect.Request[v1.DiscoverTechRequest]) (*connect.Response[v1.DiscoverTechResponse], error) {
	return c.discoverTech.CallUnary(ctx, req)
}

// GetGlobalConfig calls gateon.v1.ApiService.GetGlobalConfig.
func (c *apiServiceClient) GetGlobalConfig(ctx context.Context, req *connect.Request[v1.GetGlobalConfigRequest]) (*connect.Response[v1.GetGlobalConfigResponse], error) {
	return c.getGlobalConfig.CallUnary(ctx, req)
}

// UpdateGlobalConfig calls gateon.v1.ApiService.UpdateGlobalConfig.
func (c *apiServiceClient) UpdateGlobalConfig(ctx context.Context, req *connect.Request[v1.UpdateGlobalConfigRequest]) (*connect.Response[v1.UpdateGlobalConfigResponse], error) {
	return c.updateGlobalConfig.CallUnary(ctx, req)
}

// ListEntryPoints calls gateon.v1.ApiService.ListEntryPoints.
func (c *apiServiceClient) ListEntryPoints(ctx context.Context, req *connect.Request[v1.ListEntryPointsRequest]) (*connect.Response[v1.ListEntryPointsResponse], error) {
	return c.listEntryPoints.CallUnary(ctx, req)
}

// UpdateEntryPoint calls gateon.v1.ApiService.UpdateEntryPoint.
func (c *apiServiceClient) UpdateEntryPoint(ctx context.Context, req *connect.Request[v1.UpdateEntryPointRequest]) (*connect.Response[v1.UpdateEntryPointResponse], error) {
	return c.updateEntryPoint.CallUnary(ctx, req)
}

// DeleteEntryPoint calls gateon.v1.ApiService.DeleteEntryPoint.
func (c *apiServiceClient) DeleteEntryPoint(ctx context.Context, req *connect.Request[v1.DeleteEntryPointRequest]) (*connect.Response[v1.DeleteEntryPointResponse], error) {
	return c.deleteEntryPoint.CallUnary(ctx, req)
}

// ListMiddlewares calls gateon.v1.ApiService.ListMiddlewares.
func (c *apiServiceClient) ListMiddlewares(ctx context.Context, req *connect.Request[v1.ListMiddlewaresRequest]) (*connect.Response[v1.ListMiddlewaresResponse], error) {
	return c.listMiddlewares.CallUnary(ctx, req)
}

// UpdateMiddleware calls gateon.v1.ApiService.UpdateMiddleware.
func (c *apiServiceClient) UpdateMiddleware(ctx context.Context, req *connect.Request[v1.UpdateMiddlewareRequest]) (*connect.Response[v1.UpdateMiddlewareResponse], error) {
	return c.updateMiddleware.CallUnary(ctx, req)
}

// DeleteMiddleware calls gateon.v1.ApiService.DeleteMiddleware.
func (c *apiServiceClient) DeleteMiddleware(ctx context.Context, req *connect.Request[v1.DeleteMiddlewareRequest]) (*connect.Response[v1.DeleteMiddlewareResponse], error) {
	return c.deleteMiddleware.CallUnary(ctx, req)
}

// GetCloudflareIPs calls gateon.v1.ApiService.GetCloudflareIPs.
func (c *apiServiceClient) GetCloudflareIPs(ctx context.Context, req *connect.Request[v1.GetCloudflareIPsRequest]) (*connect.Response[v1.GetCloudflareIPsResponse], error) {
	return c.getCloudflareIPs.CallUnary(ctx, req)
}

// ListTLSOptions calls gateon.v1.ApiService.ListTLSOptions.
func (c *apiServiceClient) ListTLSOptions(ctx context.Context, req *connect.Request[v1.ListTLSOptionsRequest]) (*connect.Response[v1.ListTLSOptionsResponse], error) {
	return c.listTLSOptions.CallUnary(ctx, req)
}

// UpdateTLSOption calls gateon.v1.ApiService.UpdateTLSOption.
func (c *apiServiceClient) UpdateTLSOption(ctx context.Context, req *connect.Request[v1.UpdateTLSOptionRequest]) (*connect.Response[v1.UpdateTLSOptionResponse], error) {
	return c.updateTLSOption.CallUnary(ctx, req)
}

// DeleteTLSOption calls gateon.v1.ApiService.DeleteTLSOption.
func (c *apiServiceClient) DeleteTLSOption(ctx context.Context, req *connect.Request[v1.DeleteTLSOptionRequest]) (*connect.Response[v1.DeleteTLSOptionResponse], error) {
	return c.deleteTLSOption.CallUnary(ctx, req)
}

// Login calls gateon.v1.ApiService.Login.
func (c *apiServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// IsSetupRequired calls gateon.v1.ApiService.IsSetupRequired.
func (c *apiServiceClient) IsSetupRequired(ctx context.Context, req *connect.Request[v1.IsSetupRequiredRequest]) (*connect.Response[v1.IsSetupRequiredResponse], error) {
	return c.isSetupRequired.CallUnary(ctx, req)
}

// Setup calls gateon.v1.ApiService.Setup.
func (c *apiServiceClient) Setup(ctx context.Context, req *connect.Request[v1.SetupRequest]) (*connect.Response[v1.SetupResponse], error) {
	return c.setup.CallUnary(ctx, req)
}

// ChangePassword calls gateon.v1.ApiService.ChangePassword.
func (c *apiServiceClient) ChangePassword(ctx context.Context, req *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error) {
	return c.changePassword.CallUnary(ctx, req)
}

// ListUsers calls gateon.v1.ApiService.ListUsers.
func (c *apiServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// UpdateUser calls gateon.v1.ApiService.UpdateUser.
func (c *apiServiceClient) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls gateon.v1.ApiService.DeleteUser.
func (c *apiServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// GetDiagnostics calls gateon.v1.ApiService.GetDiagnostics.
func (c *apiServiceClient) GetDiagnostics(ctx context.Context, req *connect.Request[v1.GetDiagnosticsRequest]) (*connect.Response[v1.GetDiagnosticsResponse], error) {
	return c.getDiagnostics.CallUnary(ctx, req)
}

// ListSecurityThreats calls gateon.v1.ApiService.ListSecurityThreats.
func (c *apiServiceClient) ListSecurityThreats(ctx context.Context, req *connect.Request[v1.ListSecurityThreatsRequest]) (*connect.Response[v1.ListSecurityThreatsResponse], error) {
	return c.listSecurityThreats.CallUnary(ctx, req)
}

// GetSecurityThreat calls gateon.v1.ApiService.GetSecurityThreat.
func (c *apiServiceClient) GetSecurityThreat(ctx context.Context, req *connect.Request[v1.GetSecurityThreatRequest]) (*connect.Response[v1.GetSecurityThreatResponse], error) {
	return c.getSecurityThreat.CallUnary(ctx, req)
}

// MitigateThreat calls gateon.v1.ApiService.MitigateThreat.
func (c *apiServiceClient) MitigateThreat(ctx context.Context, req *connect.Request[v1.MitigateThreatRequest]) (*connect.Response[v1.MitigateThreatResponse], error) {
	return c.mitigateThreat.CallUnary(ctx, req)
}

// RemoveMitigatedThreat calls gateon.v1.ApiService.RemoveMitigatedThreat.
func (c *apiServiceClient) RemoveMitigatedThreat(ctx context.Context, req *connect.Request[v1.RemoveMitigatedThreatRequest]) (*connect.Response[v1.RemoveMitigatedThreatResponse], error) {
	return c.removeMitigatedThreat.CallUnary(ctx, req)
}

// ListReputations calls gateon.v1.ApiService.ListReputations.
func (c *apiServiceClient) ListReputations(ctx context.Context, req *connect.Request[v1.ListReputationsRequest]) (*connect.Response[v1.ListReputationsResponse], error) {
	return c.listReputations.CallUnary(ctx, req)
}

// ListAuditLogs calls gateon.v1.ApiService.ListAuditLogs.
func (c *apiServiceClient) ListAuditLogs(ctx context.Context, req *connect.Request[v1.ListAuditLogsRequest]) (*connect.Response[v1.ListAuditLogsResponse], error) {
	return c.listAuditLogs.CallUnary(ctx, req)
}

// ListAuditArchives calls gateon.v1.ApiService.ListAuditArchives.
func (c *apiServiceClient) ListAuditArchives(ctx context.Context, req *connect.Request[v1.ListAuditArchivesRequest]) (*connect.Response[v1.ListAuditArchivesResponse], error) {
	return c.listAuditArchives.CallUnary(ctx, req)
}

// GetAuditArchive calls gateon.v1.ApiService.GetAuditArchive.
func (c *apiServiceClient) GetAuditArchive(ctx context.Context, req *connect.Request[v1.GetAuditArchiveRequest]) (*connect.Response[v1.GetAuditArchiveResponse], error) {
	return c.getAuditArchive.CallUnary(ctx, req)
}

// ApplyRecommendation calls gateon.v1.ApiService.ApplyRecommendation.
func (c *apiServiceClient) ApplyRecommendation(ctx context.Context, req *connect.Request[v1.ApplyRecommendationRequest]) (*connect.Response[v1.ApplyRecommendationResponse], error) {
	return c.applyRecommendation.CallUnary(ctx, req)
}

// TriggerWafUpdate calls gateon.v1.ApiService.TriggerWafUpdate.
func (c *apiServiceClient) TriggerWafUpdate(ctx context.Context, req *connect.Request[v1.TriggerWafUpdateRequest]) (*connect.Response[v1.TriggerWafUpdateResponse], error) {
	return c.triggerWafUpdate.CallUnary(ctx, req)
}

// TraceRoute calls gateon.v1.ApiService.TraceRoute.
func (c *apiServiceClient) TraceRoute(ctx context.Context, req *connect.Request[v1.TraceRouteRequest]) (*connect.Response[v1.TraceRouteResponse], error) {
	return c.traceRoute.CallUnary(ctx, req)
}

// ValidateCORS calls gateon.v1.ApiService.ValidateCORS.
func (c *apiServiceClient) ValidateCORS(ctx context.Context, req *connect.Request[v1.ValidateCORSRequest]) (*connect.Response[v1.ValidateCORSResponse], error) {
	return c.validateCORS.CallUnary(ctx, req)
}

// InstallClamav calls gateon.v1.ApiService.InstallClamav.
func (c *apiServiceClient) InstallClamav(ctx context.Context, req *connect.Request[v1.InstallClamavRequest]) (*connect.Response[v1.InstallClamavResponse], error) {
	return c.installClamav.CallUnary(ctx, req)
}

// UninstallClamav calls gateon.v1.ApiService.UninstallClamav.
func (c *apiServiceClient) UninstallClamav(ctx context.Context, req *connect.Request[v1.UninstallClamavRequest]) (*connect.Response[v1.UninstallClamavResponse], error) {
	return c.uninstallClamav.CallUnary(ctx, req)
}

// RunDeepScan calls gateon.v1.ApiService.RunDeepScan.
func (c *apiServiceClient) RunDeepScan(ctx context.Context, req *connect.Request[v1.RunDeepScanRequest]) (*connect.Response[v1.RunDeepScanResponse], error) {
	return c.runDeepScan.CallUnary(ctx, req)
}

// ListWafRules calls gateon.v1.ApiService.ListWafRules.
func (c *apiServiceClient) ListWafRules(ctx context.Context, req *connect.Request[v1.ListWafRulesRequest]) (*connect.Response[v1.ListWafRulesResponse], error) {
	return c.listWafRules.CallUnary(ctx, req)
}

// CreateWafRule calls gateon.v1.ApiService.CreateWafRule.
func (c *apiServiceClient) CreateWafRule(ctx context.Context, req *connect.Request[v1.CreateWafRuleRequest]) (*connect.Response[v1.CreateWafRuleResponse], error) {
	return c.createWafRule.CallUnary(ctx, req)
}

// UpdateWafRule calls gateon.v1.ApiService.UpdateWafRule.
func (c *apiServiceClient) UpdateWafRule(ctx context.Context, req *connect.Request[v1.UpdateWafRuleRequest]) (*connect.Response[v1.UpdateWafRuleResponse], error) {
	return c.updateWafRule.CallUnary(ctx, req)
}

// DeleteWafRule calls gateon.v1.ApiService.DeleteWafRule.
func (c *apiServiceClient) DeleteWafRule(ctx context.Context, req *connect.Request[v1.DeleteWafRuleRequest]) (*connect.Response[v1.DeleteWafRuleResponse], error) {
	return c.deleteWafRule.CallUnary(ctx, req)
}

// ApiServiceHandler is an implementation of the gateon.v1.ApiService service.
type ApiServiceHandler interface {
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	ListTraces(context.Context, *connect.Request[v1.ListTracesRequest]) (*connect.Response[v1.ListTracesResponse], error)
	GetTrace(context.Context, *connect.Request[v1.GetTraceRequest]) (*connect.Response[v1.GetTraceResponse], error)
	ListRoutes(context.Context, *connect.Request[v1.ListRoutesRequest]) (*connect.Response[v1.ListRoutesResponse], error)
	UpdateRoute(context.Context, *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error)
	DeleteRoute(context.Context, *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[v1.DeleteRouteResponse], error)
	ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error)
	UpdateService(context.Context, *connect.Request[v1.UpdateServiceRequest]) (*connect.Response[v1.UpdateServiceResponse], error)
	DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error)
	DiscoverGrpcServices(context.Context, *connect.Request[v1.DiscoverGrpcServicesRequest]) (*connect.Response[v1.DiscoverGrpcServicesResponse], error)
	DiscoverTech(context.Context, *connect.Request[v1.DiscoverTechRequest]) (*connect.Response[v1.DiscoverTechResponse], error)
	GetGlobalConfig(context.Context, *connect.Request[v1.GetGlobalConfigRequest]) (*connect.Response[v1.GetGlobalConfigResponse], error)
	UpdateGlobalConfig(context.Context, *connect.Request[v1.UpdateGlobalConfigRequest]) (*connect.Response[v1.UpdateGlobalConfigResponse], error)
	ListEntryPoints(context.Context, *connect.Request[v1.ListEntryPointsRequest]) (*connect.Response[v1.ListEntryPointsResponse], error)
	UpdateEntryPoint(context.Context, *connect.Request[v1.UpdateEntryPointRequest]) (*connect.Response[v1.UpdateEntryPointResponse], error)
	DeleteEntryPoint(context.Context, *connect.Request[v1.DeleteEntryPointRequest]) (*connect.Response[v1.DeleteEntryPointResponse], error)
	ListMiddlewares(context.Context, *connect.Request[v1.ListMiddlewaresRequest]) (*connect.Response[v1.ListMiddlewaresResponse], error)
	UpdateMiddleware(context.Context, *connect.Request[v1.UpdateMiddlewareRequest]) (*connect.Response[v1.UpdateMiddlewareResponse], error)
	DeleteMiddleware(context.Context, *connect.Request[v1.DeleteMiddlewareRequest]) (*connect.Response[v1.DeleteMiddlewareResponse], error)
	GetCloudflareIPs(context.Context, *connect.Request[v1.GetCloudflareIPsRequest]) (*connect.Response[v1.GetCloudflareIPsResponse], error)
	ListTLSOptions(context.Context, *connect.Request[v1.ListTLSOptionsRequest]) (*connect.Response[v1.ListTLSOptionsResponse], error)
	UpdateTLSOption(context.Context, *connect.Request[v1.UpdateTLSOptionRequest]) (*connect.Response[v1.UpdateTLSOptionResponse], error)
	DeleteTLSOption(context.Context, *connect.Request[v1.DeleteTLSOptionRequest]) (*connect.Response[v1.DeleteTLSOptionResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	IsSetupRequired(context.Context, *connect.Request[v1.IsSetupRequiredRequest]) (*connect.Response[v1.IsSetupRequiredResponse], error)
	Setup(context.Context, *connect.Request[v1.SetupRequest]) (*connect.Response[v1.SetupResponse], error)
	ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error)
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	GetDiagnostics(context.Context, *connect.Request[v1.GetDiagnosticsRequest]) (*connect.Response[v1.GetDiagnosticsResponse], error)
	ListSecurityThreats(context.Context, *connect.Request[v1.ListSecurityThreatsRequest]) (*connect.Response[v1.ListSecurityThreatsResponse], error)
	GetSecurityThreat(context.Context, *connect.Request[v1.GetSecurityThreatRequest]) (*connect.Response[v1.GetSecurityThreatResponse], error)
	MitigateThreat(context.Context, *connect.Request[v1.MitigateThreatRequest]) (*connect.Response[v1.MitigateThreatResponse], error)
	RemoveMitigatedThreat(context.Context, *connect.Request[v1.RemoveMitigatedThreatRequest]) (*connect.Response[v1.RemoveMitigatedThreatResponse], error)
	ListReputations(context.Context, *connect.Request[v1.ListReputationsRequest]) (*connect.Response[v1.ListReputationsResponse], error)
	ListAuditLogs(context.Context, *connect.Request[v1.ListAuditLogsRequest]) (*connect.Response[v1.ListAuditLogsResponse], error)
	ListAuditArchives(context.Context, *connect.Request[v1.ListAuditArchivesRequest]) (*connect.Response[v1.ListAuditArchivesResponse], error)
	GetAuditArchive(context.Context, *connect.Request[v1.GetAuditArchiveRequest]) (*connect.Response[v1.GetAuditArchiveResponse], error)
	ApplyRecommendation(context.Context, *connect.Request[v1.ApplyRecommendationRequest]) (*connect.Response[v1.ApplyRecommendationResponse], error)
	TriggerWafUpdate(context.Context, *connect.Request[v1.TriggerWafUpdateRequest]) (*connect.Response[v1.TriggerWafUpdateResponse], error)
	TraceRoute(context.Context, *connect.Request[v1.TraceRouteRequest]) (*connect.Response[v1.TraceRouteResponse], error)
	ValidateCORS(context.Context, *connect.Request[v1.ValidateCORSRequest]) (*connect.Response[v1.ValidateCORSResponse], error)
	InstallClamav(context.Context, *connect.Request[v1.InstallClamavRequest]) (*connect.Response[v1.InstallClamavResponse], error)
	UninstallClamav(context.Context, *connect.Request[v1.UninstallClamavRequest]) (*connect.Response[v1.UninstallClamavResponse], error)
	RunDeepScan(context.Context, *connect.Request[v1.RunDeepScanRequest]) (*connect.Response[v1.RunDeepScanResponse], error)
	ListWafRules(context.Context, *connect.Request[v1.ListWafRulesRequest]) (*connect.Response[v1.ListWafRulesResponse], error)
	CreateWafRule(context.Context, *connect.Request[v1.CreateWafRuleRequest]) (*connect.Response[v1.CreateWafRuleResponse], error)
	UpdateWafRule(context.Context, *connect.Request[v1.UpdateWafRuleRequest]) (*connect.Response[v1.UpdateWafRuleResponse], error)
	DeleteWafRule(context.Context, *connect.Request[v1.DeleteWafRuleRequest]) (*connect.Response[v1.DeleteWafRuleResponse], error)
}

// NewApiServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApiServiceHandler(svc ApiServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	apiServiceMethods := v1.File_gateon_v1_api_proto.Services().ByName("ApiService").Methods()
	apiServiceGetStatusHandler := connect.NewUnaryHandler(
		ApiServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(apiServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListTracesHandler := connect.NewUnaryHandler(
		ApiServiceListTracesProcedure,
		svc.ListTraces,
		connect.WithSchema(apiServiceMethods.ByName("ListTraces")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceGetTraceHandler := connect.NewUnaryHandler(
		ApiServiceGetTraceProcedure,
		svc.GetTrace,
		connect.WithSchema(apiServiceMethods.ByName("GetTrace")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListRoutesHandler := connect.NewUnaryHandler(
		ApiServiceListRoutesProcedure,
		svc.ListRoutes,
		connect.WithSchema(apiServiceMethods.ByName("ListRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateRouteHandler := connect.NewUnaryHandler(
		ApiServiceUpdateRouteProcedure,
		svc.UpdateRoute,
		connect.WithSchema(apiServiceMethods.ByName("UpdateRoute")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteRouteHandler := connect.NewUnaryHandler(
		ApiServiceDeleteRouteProcedure,
		svc.DeleteRoute,
		connect.WithSchema(apiServiceMethods.ByName("DeleteRoute")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListServicesHandler := connect.NewUnaryHandler(
		ApiServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(apiServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateServiceHandler := connect.NewUnaryHandler(
		ApiServiceUpdateServiceProcedure,
		svc.UpdateService,
		connect.WithSchema(apiServiceMethods.ByName("UpdateService")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteServiceHandler := connect.NewUnaryHandler(
		ApiServiceDeleteServiceProcedure,
		svc.DeleteService,
		connect.WithSchema(apiServiceMethods.ByName("DeleteService")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDiscoverGrpcServicesHandler := connect.NewUnaryHandler(
		ApiServiceDiscoverGrpcServicesProcedure,
		svc.DiscoverGrpcServices,
		connect.WithSchema(apiServiceMethods.ByName("DiscoverGrpcServices")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDiscoverTechHandler := connect.NewUnaryHandler(
		ApiServiceDiscoverTechProcedure,
		svc.DiscoverTech,
		connect.WithSchema(apiServiceMethods.ByName("DiscoverTech")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceGetGlobalConfigHandler := connect.NewUnaryHandler(
		ApiServiceGetGlobalConfigProcedure,
		svc.GetGlobalConfig,
		connect.WithSchema(apiServiceMethods.ByName("GetGlobalConfig")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateGlobalConfigHandler := connect.NewUnaryHandler(
		ApiServiceUpdateGlobalConfigProcedure,
		svc.UpdateGlobalConfig,
		connect.WithSchema(apiServiceMethods.ByName("UpdateGlobalConfig")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListEntryPointsHandler := connect.NewUnaryHandler(
		ApiServiceListEntryPointsProcedure,
		svc.ListEntryPoints,
		connect.WithSchema(apiServiceMethods.ByName("ListEntryPoints")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateEntryPointHandler := connect.NewUnaryHandler(
		ApiServiceUpdateEntryPointProcedure,
		svc.UpdateEntryPoint,
		connect.WithSchema(apiServiceMethods.ByName("UpdateEntryPoint")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteEntryPointHandler := connect.NewUnaryHandler(
		ApiServiceDeleteEntryPointProcedure,
		svc.DeleteEntryPoint,
		connect.WithSchema(apiServiceMethods.ByName("DeleteEntryPoint")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListMiddlewaresHandler := connect.NewUnaryHandler(
		ApiServiceListMiddlewaresProcedure,
		svc.ListMiddlewares,
		connect.WithSchema(apiServiceMethods.ByName("ListMiddlewares")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateMiddlewareHandler := connect.NewUnaryHandler(
		ApiServiceUpdateMiddlewareProcedure,
		svc.UpdateMiddleware,
		connect.WithSchema(apiServiceMethods.ByName("UpdateMiddleware")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteMiddlewareHandler := connect.NewUnaryHandler(
		ApiServiceDeleteMiddlewareProcedure,
		svc.DeleteMiddleware,
		connect.WithSchema(apiServiceMethods.ByName("DeleteMiddleware")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceGetCloudflareIPsHandler := connect.NewUnaryHandler(
		ApiServiceGetCloudflareIPsProcedure,
		svc.GetCloudflareIPs,
		connect.WithSchema(apiServiceMethods.ByName("GetCloudflareIPs")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListTLSOptionsHandler := connect.NewUnaryHandler(
		ApiServiceListTLSOptionsProcedure,
		svc.ListTLSOptions,
		connect.WithSchema(apiServiceMethods.ByName("ListTLSOptions")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateTLSOptionHandler := connect.NewUnaryHandler(
		ApiServiceUpdateTLSOptionProcedure,
		svc.UpdateTLSOption,
		connect.WithSchema(apiServiceMethods.ByName("UpdateTLSOption")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteTLSOptionHandler := connect.NewUnaryHandler(
		ApiServiceDeleteTLSOptionProcedure,
		svc.DeleteTLSOption,
		connect.WithSchema(apiServiceMethods.ByName("DeleteTLSOption")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceLoginHandler := connect.NewUnaryHandler(
		ApiServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(apiServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceIsSetupRequiredHandler := connect.NewUnaryHandler(
		ApiServiceIsSetupRequiredProcedure,
		svc.IsSetupRequired,
		connect.WithSchema(apiServiceMethods.ByName("IsSetupRequired")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceSetupHandler := connect.NewUnaryHandler(
		ApiServiceSetupProcedure,
		svc.Setup,
		connect.WithSchema(apiServiceMethods.ByName("Setup")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceChangePasswordHandler := connect.NewUnaryHandler(
		ApiServiceChangePasswordProcedure,
		svc.ChangePassword,
		connect.WithSchema(apiServiceMethods.ByName("ChangePassword")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListUsersHandler := connect.NewUnaryHandler(
		ApiServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(apiServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateUserHandler := connect.NewUnaryHandler(
		ApiServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(apiServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteUserHandler := connect.NewUnaryHandler(
		ApiServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(apiServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceGetDiagnosticsHandler := connect.NewUnaryHandler(
		ApiServiceGetDiagnosticsProcedure,
		svc.GetDiagnostics,
		connect.WithSchema(apiServiceMethods.ByName("GetDiagnostics")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListSecurityThreatsHandler := connect.NewUnaryHandler(
		ApiServiceListSecurityThreatsProcedure,
		svc.ListSecurityThreats,
		connect.WithSchema(apiServiceMethods.ByName("ListSecurityThreats")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceGetSecurityThreatHandler := connect.NewUnaryHandler(
		ApiServiceGetSecurityThreatProcedure,
		svc.GetSecurityThreat,
		connect.WithSchema(apiServiceMethods.ByName("GetSecurityThreat")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceMitigateThreatHandler := connect.NewUnaryHandler(
		ApiServiceMitigateThreatProcedure,
		svc.MitigateThreat,
		connect.WithSchema(apiServiceMethods.ByName("MitigateThreat")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceRemoveMitigatedThreatHandler := connect.NewUnaryHandler(
		ApiServiceRemoveMitigatedThreatProcedure,
		svc.RemoveMitigatedThreat,
		connect.WithSchema(apiServiceMethods.ByName("RemoveMitigatedThreat")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListReputationsHandler := connect.NewUnaryHandler(
		ApiServiceListReputationsProcedure,
		svc.ListReputations,
		connect.WithSchema(apiServiceMethods.ByName("ListReputations")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListAuditLogsHandler := connect.NewUnaryHandler(
		ApiServiceListAuditLogsProcedure,
		svc.ListAuditLogs,
		connect.WithSchema(apiServiceMethods.ByName("ListAuditLogs")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListAuditArchivesHandler := connect.NewUnaryHandler(
		ApiServiceListAuditArchivesProcedure,
		svc.ListAuditArchives,
		connect.WithSchema(apiServiceMethods.ByName("ListAuditArchives")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceGetAuditArchiveHandler := connect.NewUnaryHandler(
		ApiServiceGetAuditArchiveProcedure,
		svc.GetAuditArchive,
		connect.WithSchema(apiServiceMethods.ByName("GetAuditArchive")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceApplyRecommendationHandler := connect.NewUnaryHandler(
		ApiServiceApplyRecommendationProcedure,
		svc.ApplyRecommendation,
		connect.WithSchema(apiServiceMethods.ByName("ApplyRecommendation")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceTriggerWafUpdateHandler := connect.NewUnaryHandler(
		ApiServiceTriggerWafUpdateProcedure,
		svc.TriggerWafUpdate,
		connect.WithSchema(apiServiceMethods.ByName("TriggerWafUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceTraceRouteHandler := connect.NewUnaryHandler(
		ApiServiceTraceRouteProcedure,
		svc.TraceRoute,
		connect.WithSchema(apiServiceMethods.ByName("TraceRoute")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceValidateCORSHandler := connect.NewUnaryHandler(
		ApiServiceValidateCORSProcedure,
		svc.ValidateCORS,
		connect.WithSchema(apiServiceMethods.ByName("ValidateCORS")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceInstallClamavHandler := connect.NewUnaryHandler(
		ApiServiceInstallClamavProcedure,
		svc.InstallClamav,
		connect.WithSchema(apiServiceMethods.ByName("InstallClamav")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUninstallClamavHandler := connect.NewUnaryHandler(
		ApiServiceUninstallClamavProcedure,
		svc.UninstallClamav,
		connect.WithSchema(apiServiceMethods.ByName("UninstallClamav")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceRunDeepScanHandler := connect.NewUnaryHandler(
		ApiServiceRunDeepScanProcedure,
		svc.RunDeepScan,
		connect.WithSchema(apiServiceMethods.ByName("RunDeepScan")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceListWafRulesHandler := connect.NewUnaryHandler(
		ApiServiceListWafRulesProcedure,
		svc.ListWafRules,
		connect.WithSchema(apiServiceMethods.ByName("ListWafRules")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceCreateWafRuleHandler := connect.NewUnaryHandler(
		ApiServiceCreateWafRuleProcedure,
		svc.CreateWafRule,
		connect.WithSchema(apiServiceMethods.ByName("CreateWafRule")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceUpdateWafRuleHandler := connect.NewUnaryHandler(
		ApiServiceUpdateWafRuleProcedure,
		svc.UpdateWafRule,
		connect.WithSchema(apiServiceMethods.ByName("UpdateWafRule")),
		connect.WithHandlerOptions(opts...),
	)
	apiServiceDeleteWafRuleHandler := connect.NewUnaryHandler(
		ApiServiceDeleteWafRuleProcedure,
		svc.DeleteWafRule,
		connect.WithSchema(apiServiceMethods.ByName("DeleteWafRule")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gateon.v1.ApiService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApiServiceGetStatusProcedure:
			apiServiceGetStatusHandler.ServeHTTP(w, r)
		case ApiServiceListTracesProcedure:
			apiServiceListTracesHandler.ServeHTTP(w, r)
		case ApiServiceGetTraceProcedure:
			apiServiceGetTraceHandler.ServeHTTP(w, r)
		case ApiServiceListRoutesProcedure:
			apiServiceListRoutesHandler.ServeHTTP(w, r)
		case ApiServiceUpdateRouteProcedure:
			apiServiceUpdateRouteHandler.ServeHTTP(w, r)
		case ApiServiceDeleteRouteProcedure:
			apiServiceDeleteRouteHandler.ServeHTTP(w, r)
		case ApiServiceListServicesProcedure:
			apiServiceListServicesHandler.ServeHTTP(w, r)
		case ApiServiceUpdateServiceProcedure:
			apiServiceUpdateServiceHandler.ServeHTTP(w, r)
		case ApiServiceDeleteServiceProcedure:
			apiServiceDeleteServiceHandler.ServeHTTP(w, r)
		case ApiServiceDiscoverGrpcServicesProcedure:
			apiServiceDiscoverGrpcServicesHandler.ServeHTTP(w, r)
		case ApiServiceDiscoverTechProcedure:
			apiServiceDiscoverTechHandler.ServeHTTP(w, r)
		case ApiServiceGetGlobalConfigProcedure:
			apiServiceGetGlobalConfigHandler.ServeHTTP(w, r)
		case ApiServiceUpdateGlobalConfigProcedure:
			apiServiceUpdateGlobalConfigHandler.ServeHTTP(w, r)
		case ApiServiceListEntryPointsProcedure:
			apiServiceListEntryPointsHandler.ServeHTTP(w, r)
		case ApiServiceUpdateEntryPointProcedure:
			apiServiceUpdateEntryPointHandler.ServeHTTP(w, r)
		case ApiServiceDeleteEntryPointProcedure:
			apiServiceDeleteEntryPointHandler.ServeHTTP(w, r)
		case ApiServiceListMiddlewaresProcedure:
			apiServiceListMiddlewaresHandler.ServeHTTP(w, r)
		case ApiServiceUpdateMiddlewareProcedure:
			apiServiceUpdateMiddlewareHandler.ServeHTTP(w, r)
		case ApiServiceDeleteMiddlewareProcedure:
			apiServiceDeleteMiddlewareHandler.ServeHTTP(w, r)
		case ApiServiceGetCloudflareIPsProcedure:
			apiServiceGetCloudflareIPsHandler.ServeHTTP(w, r)
		case ApiServiceListTLSOptionsProcedure:
			apiServiceListTLSOptionsHandler.ServeHTTP(w, r)
		case ApiServiceUpdateTLSOptionProcedure:
			apiServiceUpdateTLSOptionHandler.ServeHTTP(w, r)
		case ApiServiceDeleteTLSOptionProcedure:
			apiServiceDeleteTLSOptionHandler.ServeHTTP(w, r)
		case ApiServiceLoginProcedure:
			apiServiceLoginHandler.ServeHTTP(w, r)
		case ApiServiceIsSetupRequiredProcedure:
			apiServiceIsSetupRequiredHandler.ServeHTTP(w, r)
		case ApiServiceSetupProcedure:
			apiServiceSetupHandler.ServeHTTP(w, r)
		case ApiServiceChangePasswordProcedure:
			apiServiceChangePasswordHandler.ServeHTTP(w, r)
		case ApiServiceListUsersProcedure:
			apiServiceListUsersHandler.ServeHTTP(w, r)
		case ApiServiceUpdateUserProcedure:
			apiServiceUpdateUserHandler.ServeHTTP(w, r)
		case ApiServiceDeleteUserProcedure:
			apiServiceDeleteUserHandler.ServeHTTP(w, r)
		case ApiServiceGetDiagnosticsProcedure:
			apiServiceGetDiagnosticsHandler.ServeHTTP(w, r)
		case ApiServiceListSecurityThreatsProcedure:
			apiServiceListSecurityThreatsHandler.ServeHTTP(w, r)
		case ApiServiceGetSecurityThreatProcedure:
			apiServiceGetSecurityThreatHandler.ServeHTTP(w, r)
		case ApiServiceMitigateThreatProcedure:
			apiServiceMitigateThreatHandler.ServeHTTP(w, r)
		case ApiServiceRemoveMitigatedThreatProcedure:
			apiServiceRemoveMitigatedThreatHandler.ServeHTTP(w, r)
		case ApiServiceListReputationsProcedure:
			apiServiceListReputationsHandler.ServeHTTP(w, r)
		case ApiServiceListAuditLogsProcedure:
			apiServiceListAuditLogsHandler.ServeHTTP(w, r)
		case ApiServiceListAuditArchivesProcedure:
			apiServiceListAuditArchivesHandler.ServeHTTP(w, r)
		case ApiServiceGetAuditArchiveProcedure:
			apiServiceGetAuditArchiveHandler.ServeHTTP(w, r)
		case ApiServiceApplyRecommendationProcedure:
			apiServiceApplyRecommendationHandler.ServeHTTP(w, r)
		case ApiServiceTriggerWafUpdateProcedure:
			apiServiceTriggerWafUpdateHandler.ServeHTTP(w, r)
		case ApiServiceTraceRouteProcedure:
			apiServiceTraceRouteHandler.ServeHTTP(w, r)
		case ApiServiceValidateCORSProcedure:
			apiServiceValidateCORSHandler.ServeHTTP(w, r)
		case ApiServiceInstallClamavProcedure:
			apiServiceInstallClamavHandler.ServeHTTP(w, r)
		case ApiServiceUninstallClamavProcedure:
			apiServiceUninstallClamavHandler.ServeHTTP(w, r)
		case ApiServiceRunDeepScanProcedure:
			apiServiceRunDeepScanHandler.ServeHTTP(w, r)
		case ApiServiceListWafRulesProcedure:
			apiServiceListWafRulesHandler.ServeHTTP(w, r)
		case ApiServiceCreateWafRuleProcedure:
			apiServiceCreateWafRuleHandler.ServeHTTP(w, r)
		case ApiServiceUpdateWafRuleProcedure:
			apiServiceUpdateWafRuleHandler.ServeHTTP(w, r)
		case ApiServiceDeleteWafRuleProcedure:
			apiServiceDeleteWafRuleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApiServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApiServiceHandler struct{}

func (UnimplementedApiServiceHandler) GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetStatus is not implemented"))
}

func (UnimplementedApiServiceHandler) ListTraces(context.Context, *connect.Request[v1.ListTracesRequest]) (*connect.Response[v1.ListTracesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListTraces is not implemented"))
}

func (UnimplementedApiServiceHandler) GetTrace(context.Context, *connect.Request[v1.GetTraceRequest]) (*connect.Response[v1.GetTraceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetTrace is not implemented"))
}

func (UnimplementedApiServiceHandler) ListRoutes(context.Context, *connect.Request[v1.ListRoutesRequest]) (*connect.Response[v1.ListRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListRoutes is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateRoute(context.Context, *connect.Request[v1.UpdateRouteRequest]) (*connect.Response[v1.UpdateRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateRoute is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteRoute(context.Context, *connect.Request[v1.DeleteRouteRequest]) (*connect.Response[v1.DeleteRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteRoute is not implemented"))
}

func (UnimplementedApiServiceHandler) ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListServices is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateService(context.Context, *connect.Request[v1.UpdateServiceRequest]) (*connect.Response[v1.UpdateServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateService is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteService is not implemented"))
}

func (UnimplementedApiServiceHandler) DiscoverGrpcServices(context.Context, *connect.Request[v1.DiscoverGrpcServicesRequest]) (*connect.Response[v1.DiscoverGrpcServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DiscoverGrpcServices is not implemented"))
}

func (UnimplementedApiServiceHandler) DiscoverTech(context.Context, *connect.Request[v1.DiscoverTechRequest]) (*connect.Response[v1.DiscoverTechResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DiscoverTech is not implemented"))
}

func (UnimplementedApiServiceHandler) GetGlobalConfig(context.Context, *connect.Request[v1.GetGlobalConfigRequest]) (*connect.Response[v1.GetGlobalConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetGlobalConfig is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateGlobalConfig(context.Context, *connect.Request[v1.UpdateGlobalConfigRequest]) (*connect.Response[v1.UpdateGlobalConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateGlobalConfig is not implemented"))
}

func (UnimplementedApiServiceHandler) ListEntryPoints(context.Context, *connect.Request[v1.ListEntryPointsRequest]) (*connect.Response[v1.ListEntryPointsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListEntryPoints is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateEntryPoint(context.Context, *connect.Request[v1.UpdateEntryPointRequest]) (*connect.Response[v1.UpdateEntryPointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateEntryPoint is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteEntryPoint(context.Context, *connect.Request[v1.DeleteEntryPointRequest]) (*connect.Response[v1.DeleteEntryPointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteEntryPoint is not implemented"))
}

func (UnimplementedApiServiceHandler) ListMiddlewares(context.Context, *connect.Request[v1.ListMiddlewaresRequest]) (*connect.Response[v1.ListMiddlewaresResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListMiddlewares is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateMiddleware(context.Context, *connect.Request[v1.UpdateMiddlewareRequest]) (*connect.Response[v1.UpdateMiddlewareResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateMiddleware is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteMiddleware(context.Context, *connect.Request[v1.DeleteMiddlewareRequest]) (*connect.Response[v1.DeleteMiddlewareResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteMiddleware is not implemented"))
}

func (UnimplementedApiServiceHandler) GetCloudflareIPs(context.Context, *connect.Request[v1.GetCloudflareIPsRequest]) (*connect.Response[v1.GetCloudflareIPsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetCloudflareIPs is not implemented"))
}

func (UnimplementedApiServiceHandler) ListTLSOptions(context.Context, *connect.Request[v1.ListTLSOptionsRequest]) (*connect.Response[v1.ListTLSOptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListTLSOptions is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateTLSOption(context.Context, *connect.Request[v1.UpdateTLSOptionRequest]) (*connect.Response[v1.UpdateTLSOptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateTLSOption is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteTLSOption(context.Context, *connect.Request[v1.DeleteTLSOptionRequest]) (*connect.Response[v1.DeleteTLSOptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteTLSOption is not implemented"))
}

func (UnimplementedApiServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.Login is not implemented"))
}

func (UnimplementedApiServiceHandler) IsSetupRequired(context.Context, *connect.Request[v1.IsSetupRequiredRequest]) (*connect.Response[v1.IsSetupRequiredResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.IsSetupRequired is not implemented"))
}

func (UnimplementedApiServiceHandler) Setup(context.Context, *connect.Request[v1.SetupRequest]) (*connect.Response[v1.SetupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.Setup is not implemented"))
}

func (UnimplementedApiServiceHandler) ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ChangePassword is not implemented"))
}

func (UnimplementedApiServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListUsers is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateUser is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteUser is not implemented"))
}

func (UnimplementedApiServiceHandler) GetDiagnostics(context.Context, *connect.Request[v1.GetDiagnosticsRequest]) (*connect.Response[v1.GetDiagnosticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetDiagnostics is not implemented"))
}

func (UnimplementedApiServiceHandler) ListSecurityThreats(context.Context, *connect.Request[v1.ListSecurityThreatsRequest]) (*connect.Response[v1.ListSecurityThreatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListSecurityThreats is not implemented"))
}

func (UnimplementedApiServiceHandler) GetSecurityThreat(context.Context, *connect.Request[v1.GetSecurityThreatRequest]) (*connect.Response[v1.GetSecurityThreatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetSecurityThreat is not implemented"))
}

func (UnimplementedApiServiceHandler) MitigateThreat(context.Context, *connect.Request[v1.MitigateThreatRequest]) (*connect.Response[v1.MitigateThreatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.MitigateThreat is not implemented"))
}

func (UnimplementedApiServiceHandler) RemoveMitigatedThreat(context.Context, *connect.Request[v1.RemoveMitigatedThreatRequest]) (*connect.Response[v1.RemoveMitigatedThreatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.RemoveMitigatedThreat is not implemented"))
}

func (UnimplementedApiServiceHandler) ListReputations(context.Context, *connect.Request[v1.ListReputationsRequest]) (*connect.Response[v1.ListReputationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListReputations is not implemented"))
}

func (UnimplementedApiServiceHandler) ListAuditLogs(context.Context, *connect.Request[v1.ListAuditLogsRequest]) (*connect.Response[v1.ListAuditLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListAuditLogs is not implemented"))
}

func (UnimplementedApiServiceHandler) ListAuditArchives(context.Context, *connect.Request[v1.ListAuditArchivesRequest]) (*connect.Response[v1.ListAuditArchivesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListAuditArchives is not implemented"))
}

func (UnimplementedApiServiceHandler) GetAuditArchive(context.Context, *connect.Request[v1.GetAuditArchiveRequest]) (*connect.Response[v1.GetAuditArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.GetAuditArchive is not implemented"))
}

func (UnimplementedApiServiceHandler) ApplyRecommendation(context.Context, *connect.Request[v1.ApplyRecommendationRequest]) (*connect.Response[v1.ApplyRecommendationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ApplyRecommendation is not implemented"))
}

func (UnimplementedApiServiceHandler) TriggerWafUpdate(context.Context, *connect.Request[v1.TriggerWafUpdateRequest]) (*connect.Response[v1.TriggerWafUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.TriggerWafUpdate is not implemented"))
}

func (UnimplementedApiServiceHandler) TraceRoute(context.Context, *connect.Request[v1.TraceRouteRequest]) (*connect.Response[v1.TraceRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.TraceRoute is not implemented"))
}

func (UnimplementedApiServiceHandler) ValidateCORS(context.Context, *connect.Request[v1.ValidateCORSRequest]) (*connect.Response[v1.ValidateCORSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ValidateCORS is not implemented"))
}

func (UnimplementedApiServiceHandler) InstallClamav(context.Context, *connect.Request[v1.InstallClamavRequest]) (*connect.Response[v1.InstallClamavResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.InstallClamav is not implemented"))
}

func (UnimplementedApiServiceHandler) UninstallClamav(context.Context, *connect.Request[v1.UninstallClamavRequest]) (*connect.Response[v1.UninstallClamavResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UninstallClamav is not implemented"))
}

func (UnimplementedApiServiceHandler) RunDeepScan(context.Context, *connect.Request[v1.RunDeepScanRequest]) (*connect.Response[v1.RunDeepScanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.RunDeepScan is not implemented"))
}

func (UnimplementedApiServiceHandler) ListWafRules(context.Context, *connect.Request[v1.ListWafRulesRequest]) (*connect.Response[v1.ListWafRulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.ListWafRules is not implemented"))
}

func (UnimplementedApiServiceHandler) CreateWafRule(context.Context, *connect.Request[v1.CreateWafRuleRequest]) (*connect.Response[v1.CreateWafRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.CreateWafRule is not implemented"))
}

func (UnimplementedApiServiceHandler) UpdateWafRule(context.Context, *connect.Request[v1.UpdateWafRuleRequest]) (*connect.Response[v1.UpdateWafRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.UpdateWafRule is not implemented"))
}

func (UnimplementedApiServiceHandler) DeleteWafRule(context.Context, *connect.Request[v1.DeleteWafRuleRequest]) (*connect.Response[v1.DeleteWafRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateon.v1.ApiService.DeleteWafRule is not implemented"))
}
