// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type gateon_ebpfBackend struct {
	_       structs.HostLayout
	Ip      uint32
	EthAddr [6]uint8
	_       [2]byte
}

type gateon_ebpfEbpfConfig struct {
	_                   structs.HostLayout
	MgmtPort            uint32
	EnableKnocking      uint32
	EnableMgmtWhitelist uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	gateon_ebpfMapAdaptiveLimits   = "adaptive_limits"
	gateon_ebpfMapCountryBlockMap  = "country_block_map"
	gateon_ebpfMapCuckooFilter     = "cuckoo_filter"
	gateon_ebpfMapDropStats        = "drop_stats"
	gateon_ebpfMapGlobalEbpfConfig = "global_ebpf_config"
	gateon_ebpfMapIpTelemetry      = "ip_telemetry"
	gateon_ebpfMapJa3Blocklist     = "ja3_blocklist"
	gateon_ebpfMapJa4Blocklist     = "ja4_blocklist"
	gateon_ebpfMapKnockingConfig   = "knocking_config"
	gateon_ebpfMapKnockingState    = "knocking_state"
	gateon_ebpfMapLbBackends       = "lb_backends"
	gateon_ebpfMapLbBackendsCount  = "lb_backends_count"
	gateon_ebpfMapMgmtWhitelist    = "mgmt_whitelist"
	gateon_ebpfMapPhantomPorts     = "phantom_ports"
	gateon_ebpfMapRateLimitMap     = "rate_limit_map"
	gateon_ebpfMapShunnedIps       = "shunned_ips"
	gateon_ebpfMapTcpConntrack     = "tcp_conntrack"
	gateon_ebpfMapXskMap           = "xsk_map"
	gateon_ebpfProgXdpGateonMain   = "xdp_gateon_main"
)

// loadGateon_ebpf returns the embedded CollectionSpec for gateon_ebpf.
func loadGateon_ebpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Gateon_ebpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gateon_ebpf: %w", err)
	}

	return spec, err
}

// loadGateon_ebpfObjects loads gateon_ebpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gateon_ebpfObjects
//	*gateon_ebpfPrograms
//	*gateon_ebpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGateon_ebpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadGateon_ebpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gateon_ebpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gateon_ebpfSpecs struct {
	gateon_ebpfProgramSpecs
	gateon_ebpfMapSpecs
	gateon_ebpfVariableSpecs
}

// gateon_ebpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gateon_ebpfProgramSpecs struct {
	XdpGateonMain *ebpf.ProgramSpec `ebpf:"xdp_gateon_main"`
}

// gateon_ebpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gateon_ebpfMapSpecs struct {
	AdaptiveLimits   *ebpf.MapSpec `ebpf:"adaptive_limits"`
	CountryBlockMap  *ebpf.MapSpec `ebpf:"country_block_map"`
	CuckooFilter     *ebpf.MapSpec `ebpf:"cuckoo_filter"`
	DropStats        *ebpf.MapSpec `ebpf:"drop_stats"`
	GlobalEbpfConfig *ebpf.MapSpec `ebpf:"global_ebpf_config"`
	IpTelemetry      *ebpf.MapSpec `ebpf:"ip_telemetry"`
	Ja3Blocklist     *ebpf.MapSpec `ebpf:"ja3_blocklist"`
	Ja4Blocklist     *ebpf.MapSpec `ebpf:"ja4_blocklist"`
	KnockingConfig   *ebpf.MapSpec `ebpf:"knocking_config"`
	KnockingState    *ebpf.MapSpec `ebpf:"knocking_state"`
	LbBackends       *ebpf.MapSpec `ebpf:"lb_backends"`
	LbBackendsCount  *ebpf.MapSpec `ebpf:"lb_backends_count"`
	MgmtWhitelist    *ebpf.MapSpec `ebpf:"mgmt_whitelist"`
	PhantomPorts     *ebpf.MapSpec `ebpf:"phantom_ports"`
	RateLimitMap     *ebpf.MapSpec `ebpf:"rate_limit_map"`
	ShunnedIps       *ebpf.MapSpec `ebpf:"shunned_ips"`
	TcpConntrack     *ebpf.MapSpec `ebpf:"tcp_conntrack"`
	XskMap           *ebpf.MapSpec `ebpf:"xsk_map"`
}

// gateon_ebpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gateon_ebpfVariableSpecs struct {
}

// gateon_ebpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGateon_ebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type gateon_ebpfObjects struct {
	gateon_ebpfPrograms
	gateon_ebpfMaps
	gateon_ebpfVariables
}

func (o *gateon_ebpfObjects) Close() error {
	return _Gateon_ebpfClose(
		&o.gateon_ebpfPrograms,
		&o.gateon_ebpfMaps,
	)
}

// gateon_ebpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGateon_ebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type gateon_ebpfMaps struct {
	AdaptiveLimits   *ebpf.Map `ebpf:"adaptive_limits"`
	CountryBlockMap  *ebpf.Map `ebpf:"country_block_map"`
	CuckooFilter     *ebpf.Map `ebpf:"cuckoo_filter"`
	DropStats        *ebpf.Map `ebpf:"drop_stats"`
	GlobalEbpfConfig *ebpf.Map `ebpf:"global_ebpf_config"`
	IpTelemetry      *ebpf.Map `ebpf:"ip_telemetry"`
	Ja3Blocklist     *ebpf.Map `ebpf:"ja3_blocklist"`
	Ja4Blocklist     *ebpf.Map `ebpf:"ja4_blocklist"`
	KnockingConfig   *ebpf.Map `ebpf:"knocking_config"`
	KnockingState    *ebpf.Map `ebpf:"knocking_state"`
	LbBackends       *ebpf.Map `ebpf:"lb_backends"`
	LbBackendsCount  *ebpf.Map `ebpf:"lb_backends_count"`
	MgmtWhitelist    *ebpf.Map `ebpf:"mgmt_whitelist"`
	PhantomPorts     *ebpf.Map `ebpf:"phantom_ports"`
	RateLimitMap     *ebpf.Map `ebpf:"rate_limit_map"`
	ShunnedIps       *ebpf.Map `ebpf:"shunned_ips"`
	TcpConntrack     *ebpf.Map `ebpf:"tcp_conntrack"`
	XskMap           *ebpf.Map `ebpf:"xsk_map"`
}

func (m *gateon_ebpfMaps) Close() error {
	return _Gateon_ebpfClose(
		m.AdaptiveLimits,
		m.CountryBlockMap,
		m.CuckooFilter,
		m.DropStats,
		m.GlobalEbpfConfig,
		m.IpTelemetry,
		m.Ja3Blocklist,
		m.Ja4Blocklist,
		m.KnockingConfig,
		m.KnockingState,
		m.LbBackends,
		m.LbBackendsCount,
		m.MgmtWhitelist,
		m.PhantomPorts,
		m.RateLimitMap,
		m.ShunnedIps,
		m.TcpConntrack,
		m.XskMap,
	)
}

// gateon_ebpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGateon_ebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type gateon_ebpfVariables struct {
}

// gateon_ebpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGateon_ebpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type gateon_ebpfPrograms struct {
	XdpGateonMain *ebpf.Program `ebpf:"xdp_gateon_main"`
}

func (p *gateon_ebpfPrograms) Close() error {
	return _Gateon_ebpfClose(
		p.XdpGateonMain,
	)
}

func _Gateon_ebpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gateon_ebpf_bpf.o
var _Gateon_ebpfBytes []byte
